#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path

from docx import Document


HERE = Path(__file__).resolve().parent


def norm(text: str) -> str:
    return " ".join(text.split())


def remove_paragraph(paragraph) -> None:
    el = paragraph._element
    el.getparent().remove(el)
    paragraph._p = paragraph._element = None


def replace_paragraphs(doc: Document, replacements: dict[str, str]) -> int:
    count = 0
    for p in doc.paragraphs:
        key = norm(p.text)
        if key in replacements:
            p.text = replacements[key]
            count += 1
    return count


def find_paragraph(doc: Document, startswith: str):
    for p in doc.paragraphs:
        if norm(p.text).startswith(startswith):
            return p
    raise ValueError(f"Paragraph starting with {startswith!r} not found")


MANUSCRIPT_REPLACEMENTS = {
    norm("Figure 1 serves as the entry-point figure for the dataset, so its purpose is to show what is in clean-v1 and where direct comparative reuse is possible. We therefore organized the figure to move from overall cohort composition to receptor-level reuse potential: panel A quantifies class-by-family coverage across the 208 included systems, panels B and D show that a smaller but important subset of receptors appears in more than one G-protein-family context, panel C separates ligand-present from apo or no-ligand systems, and panel E keeps the 208-included and 14-held-back boundary explicit. The main implication is that CoupledMD is broad enough for cross-family benchmarking and within-receptor comparisons, but still curated enough that readers can see exactly which systems define the release and which records remain outside it."):
        "Figure 1 defines the scope of the clean-v1 release and the immediate reuse space it creates. We quantified class-by-family coverage, receptor-level multi-family representation, ligand context and the 208-included versus 14-held-back boundary. The figure therefore shows that CoupledMD is broad enough for cross-family benchmarking and within-receptor comparisons, while still making the cohort boundary explicit.",
    norm("Figure 2 is included to explain how the data product is organized and how a reader should move through it. We therefore show the archive hierarchy in panel A, the per-system metadata logic in panel B, the archive-first access relationship in panel C, and the practical portal/API route in panel D through search, filters, structure viewing, download actions and API entry points. The figure makes clear that CoupledMD is not only a collection of trajectories but a structured resource with a stable archival core and lighter access layers, which is important for readers deciding whether they need reproducible archive files, processed metadata, or rapid web-based inspection."):
        "Figure 2 explains how the data product is organized and how readers should navigate it. We show the archive hierarchy, the per-system metadata model, the archive-first access relationship and the portal/API route as complementary views of the same resource. The figure makes clear that CoupledMD is a structured archive with web-facing access layers rather than only a collection of trajectories.",
    norm("Figure 3 provides the main technical-validation argument for the pocket layer and also situates the scale of the release. We use panel A to ask whether known orthosteric sites are recovered often enough to trust the derived pocket annotations, and the result is positive: orthosteric-pocket recovery at the 0.85 threshold is observed in 156 of 206 systems with pocket outputs, with family-level rates of 72.5% for Gi/o, 76.1% for Gs, 83.3% for Gq/11 and 66.7% for G12/13. Panel B shows that the pocket-detection layer is not trivially sparse, with median pocket counts of 10 to 11 per system across the major families, while panel C places CoupledMD in the practical niche between single-target GPCR resources and very large general-protein MD repositories. The implication is that readers can treat the pocket layer as a technically validated reuse feature and can also see why this dataset is distinctive: it emphasizes breadth across active GPCR/G-protein complexes rather than maximal scale alone."):
        "Figure 3 provides the main technical-validation view for the pocket layer and also situates the scale of the release. Orthosteric-pocket recovery at the 0.85 threshold is observed in 156 of 206 systems with pocket outputs, with family-level rates of 72.5% for Gi/o, 76.1% for Gs, 83.3% for Gq/11 and 66.7% for G12/13, while median pocket counts remain in the 10 to 11 range across the major families. The figure therefore supports technical reuse of the pocket annotations and shows that CoupledMD occupies a useful middle ground between narrow GPCR resources and much larger general MD repositories.",
    norm("Figure 4 is the release-integrity figure, and its purpose is to show that the annotation and reduced-visualization layers are broad, checkable and transparent rather than merely appended to the archive. Panel A shows that TM-gateway open-fraction annotations are available across all 208 included systems, panel B restates the family-level orthosteric-recovery rates as a compact structural-fidelity benchmark, panel C shows that the seven gateway interfaces span a nontrivial range of open-fraction values across the cohort, and panel D links those derived records back to release control by contrasting the 208 included systems with the 14 held-back systems while also reporting the reduced-trajectory audit outcome of 205 OK systems, 3 WARN systems and 0 hard failures. The implication is that the distributed annotation and visualization tiers are usable at scale, with known caveats clearly bounded and reported rather than hidden."):
        "Figure 4 is the release-integrity figure for the annotation and reduced-visualization layers. It shows gateway coverage across all 208 included systems, nontrivial open-fraction distributions across the seven TM interfaces, the 208-included versus 14-held-back split, and the reduced-trajectory audit outcome of 205 OK systems, 3 WARN systems and 0 hard failures. The implication is that these derived layers are usable at scale and that their remaining caveats are explicitly bounded rather than hidden.",
    norm("Figure 5 is designed to show why the pocket layer is useful beyond simple validation and why it can function as a reusable atlas. Panel B shows that the consensus druggable clusters differ in both receptor coverage and mean occupancy, panel C groups those clusters into anatomical zones, panel D identifies the GPCRdb generic positions that recur most often in orthosteric and druggable cluster cores, panel E keeps the family-level orthosteric-recovery benchmark visible, and panel F highlights nomination examples with high proxy scores and representative receptors; panel A is reserved for a final structural or portal-facing snapshot to visually anchor the atlas. The main implication is that readers can use these records for cross-receptor joins, prioritization and benchmarking workflows, while still understanding that the atlas is a derived annotation layer rather than direct experimental evidence of druggability."):
        "Figure 5 shows why the pocket layer functions as a reusable atlas rather than only a validation artifact. The figure summarizes cluster coverage and occupancy, anatomical zoning, recurrent GPCRdb anchors, the family-level recovery benchmark and high-scoring nomination examples, with panel A reserved for a final structural or portal-facing snapshot. The implication is that these records can support cross-receptor joins, prioritization and benchmarking workflows, while remaining clearly framed as derived annotations rather than direct experimental evidence of druggability.",
    norm("The resource is organized around three questions that match the expectations of a Scientific Data Data Descriptor. First, what is in the release? CoupledMD provides a defined clean-v1 cohort, a transparent held-back cohort and coverage summaries by receptor class, G-protein family and ligand context. Second, can users trust the records? The release includes technical validation of pocket recovery, pocket-count distributions, reduced-trajectory frame counts and periodic-boundary audits. Third, how can users access and reuse the dataset? The archival repository is the citable data record; the web portal and REST API provide interactive and programmatic access to metadata, reduced trajectories and derived annotations; this archive-first organization is summarized in Figure 2. Third, can users trust the records? The release includes technical validation of pocket recovery, pocket-count distributions, reduced-trajectory frame counts and periodic-boundary audits."):
        "The resource is organized around three questions that match the expectations of a Scientific Data Data Descriptor. First, what is in the release? CoupledMD provides a defined clean-v1 cohort, a transparent held-back cohort and coverage summaries by receptor class, G-protein family and ligand context. Second, how is the release organized and accessed? The archival repository is the citable data record, while the web portal and REST API provide interactive and programmatic access to metadata, reduced trajectories and derived annotations; this archive-first organization is summarized in Figure 2. Third, can users trust the records? The release includes technical validation of pocket recovery, pocket-count distributions, reduced-trajectory frame counts and periodic-boundary audits.",
    norm("The reduced visualization layer was audited for frame count, atom-count agreement, blank element fields, box-mismatch flags, intra-chain breaks, inter-chain splits and scatter-frame warnings; the audit results are summarized in Technical Validation and in Supplementary Tables S15–S17."):
        "The reduced visualization layer was audited for frame count, atom-count agreement, blank element fields, box-mismatch flags, intra-chain breaks, inter-chain splits and scatter-frame warnings; the audit results are summarized in Technical Validation and in Supplementary Files S15-S17.",
    norm("Reduced-trajectory frame counts were 2,500 frames for 205 systems, 2,501 frames for two systems and 200 frames for one system. The short reduced visualization record corresponds to Gs_3SN6; the production metadata for that system remain in the clean-v1 cohort and the reduced-record difference is flagged. Systems with WARN status (Gi_8J22, Gq_7XJL and Gs_7F4H) carry only minor scatter warnings and no hard audit failure. Figure 4 summarizes gateway annotation coverage, family-level orthosteric-recovery rates, gateway open-fraction distributions and dataset completeness as the QC and integrity view of the release, while the reduced-trajectory audit details remain documented in Supplementary Tables S15-S17 and the figure callout."):
        "Reduced-trajectory frame counts were 2,500 frames for 205 systems, 2,501 frames for two systems and 200 frames for one system. The short reduced visualization record corresponds to Gs_3SN6; the production metadata for that system remain in the clean-v1 cohort and the reduced-record difference is flagged. Systems with WARN status (Gi_8J22, Gq_7XJL and Gs_7F4H) carry only minor scatter warnings and no hard audit failure. Figure 4 summarizes gateway annotation coverage, family-level orthosteric-recovery rates, gateway open-fraction distributions and dataset completeness as the QC and integrity view of the release, while the reduced-trajectory audit details remain documented in Supplementary Files S15-S17 and the figure callout.",
    norm("Example reuse workflows include filtering systems by GPCR class, G-protein family, receptor name, UniProt accession, PDB identifier or ligand annotation; retrieving reduced structures and trajectories for visualization; joining GPCRdb-mapped pocket residues to external receptor annotations; and using API endpoints to build reproducible system lists before downloading full trajectories from the archive. Figure 5 summarizes the consensus pocket annotations, GPCRdb-position anchors and proxy-validation views distributed with the resource as reusable annotation records. These workflows support rather than substitute for downstream analyses, including those that may interpret family-resolved or ligand-specific signatures."):
        "Example reuse workflows include filtering systems by GPCR class, G-protein family, receptor name, UniProt accession, PDB identifier or ligand annotation; retrieving reduced structures and trajectories for visualization; joining GPCRdb-mapped pocket residues to external receptor annotations; and using API endpoints to build reproducible system lists before downloading full trajectories from the archive. Figure 5 summarizes the pocket-atlas records distributed with the resource, including consensus clusters, recurrent GPCRdb anchors, validation context and nomination examples. These workflows support rather than substitute for downstream analyses, including those that may interpret family-resolved or ligand-specific signatures.",
    norm("CoupledMD clean-v1 covers active-state GPCR/G-protein complex systems and does not extend to inactive receptors, GPCR–arrestin complexes or ligand-free ensembles for every receptor. Because the release reflects available structural coverage, G12/13 systems are under-represented relative to Gi/o, Gs and Gq/11. The standard production design is 500 ns per replica, which may not sample slower conformational transitions. Pocket, gateway and G-protein records are derived annotations and require study-specific validation for biological interpretation. Final publication elements still pending include the archive DOI/accession, the final SHA-256 manifest, the final production-archive frame audit and the replacement of the portal screenshot placeholder in Figure 2."):
        "CoupledMD clean-v1 covers active-state GPCR/G-protein complex systems and does not extend to inactive receptors, GPCR–arrestin complexes or ligand-free ensembles for every receptor. Because the release reflects available structural coverage, G12/13 systems are under-represented relative to Gi/o, Gs and Gq/11. The standard production design is 500 ns per replica, which may not sample slower conformational transitions. Pocket, gateway and G-protein records are derived annotations and require study-specific validation for biological interpretation. Final publication elements still pending include the archive DOI/accession, the final SHA-256 manifest and the final production-archive frame audit.",
    norm("Figure 1. Coverage and reuse landscape of the CoupledMD clean-v1 release. This figure was constructed to define the scope of the release and the immediate reuse opportunities. (A) Class × G-protein-family coverage across 208 systems. (B) Receptors represented across the largest number of systems, with multi-family receptors highlighted as direct within-receptor reuse opportunities. (C) Ligand-present versus apo or no-ligand systems by family. (D) Receptor reuse landscape for the most represented receptors, with accent-colored larger markers denoting receptors sampled across more than one G-protein family. (E) Release boundary: 208 included and 14 held back from 222 designed systems, with held-back records grouped into major exclusion categories. The figure shows that the release combines broad coverage with transparent cohort definition; biological interpretation of family or ligand patterns is outside the scope of this Data Descriptor."):
        "Figure 1. Coverage and reuse landscape of the CoupledMD clean-v1 release. (A) Class × G-protein-family coverage across 208 systems. (B) Receptors represented across the largest number of systems, with multi-family receptors highlighted as direct within-receptor reuse opportunities. (C) Ligand-present versus apo or no-ligand systems by family. (D) Receptor reuse landscape for the most represented receptors, with accent-colored larger markers denoting receptors sampled across more than one G-protein family. (E) Release boundary: 208 included and 14 held back from 222 designed systems, with held-back records grouped into major exclusion categories. The figure defines release scope and reuse potential; biological interpretation of family or ligand patterns is outside the scope of this Data Descriptor.",
    norm("Figure 2. Repository organization, metadata schema and three-tier access model of CoupledMD. This figure explains how the resource is structured and accessed. (A) Archive hierarchy, including manifest, metadata, systems, topology, trajectories, reduced files, features, pocket records, QC records, code and web/API snapshots. (B) Per-system metadata schema for system, receptor, G protein, ligand/state, replicas, files and QC status. (C) Archive-first access model: the stable archive is the citable record, while the web portal and REST API provide browse, visualization and programmatic access. (D) Portal-access schematic showing search, filters, structure viewing, download actions and API entry points. The figure shows that full reproducibility depends on the archive, whereas the portal and API are optimized access layers. File formats and field definitions are detailed in Tables 2 and 3."):
        "Figure 2. Repository organization, metadata schema and three-tier access model of CoupledMD. (A) Archive hierarchy, including manifest, metadata, systems, topology, trajectories, reduced files, features, pocket records, QC records, code and web/API snapshots. (B) Per-system metadata schema for system, receptor, G protein, ligand/state, replicas, files and QC status. (C) Archive-first access model: the stable archive is the citable record, while the web portal and REST API provide browse, visualization and programmatic access. (D) Portal-access schematic showing search, filters, structure viewing, download actions and API entry points. The figure distinguishes the archival record from the web-facing access layers. File formats and field definitions are detailed in Tables 2 and 3.",
    norm("Figure 3. Technical validation and dataset-scope context for the CoupledMD clean-v1 release. This figure was designed to test the pocket layer and to place the dataset in context. (A) Best per-system orthosteric-pocket frequency by G-protein family; the dashed line marks the 0.85 recovery threshold and recovery percentages are annotated by family. (B) Per-system pocket-count distribution by family, summarized as median and interquartile range with individual-system points overlaid. (C) Descriptive comparison of system count and aggregate sampling against representative single-receptor GPCR and general-protein MD resources to contextualize the scope of CoupledMD. The results support technical reuse of the derived pocket records while showing that CoupledMD occupies a distinct middle ground between narrow single-target resources and much larger general MD repositories."):
        "Figure 3. Technical validation and dataset-scope context for the CoupledMD clean-v1 release. (A) Best per-system orthosteric-pocket frequency by G-protein family; the dashed line marks the 0.85 recovery threshold and recovery percentages are annotated by family. (B) Per-system pocket-count distribution by family, summarized as median and interquartile range with individual-system points overlaid. (C) Descriptive comparison of system count and aggregate sampling against representative single-receptor GPCR and general-protein MD resources to contextualize the scope of CoupledMD. The figure supports technical reuse of the pocket layer while showing the scale niche occupied by this release.",
    norm("Figure 4. QC and completeness summary of the CoupledMD clean-v1 release. This figure was assembled to show that the derived annotation and reduced-trajectory layers are complete enough for practical reuse and honest enough about remaining caveats. (A) Derived TM-gateway open-fraction annotations across 208 systems, grouped by G-protein family for organizational convenience; family-resolved differences in panel A are not interpreted here. (B) Orthosteric-pocket recovery rate by G-protein family, shown as a compact structural-fidelity benchmark for the derived pocket layer. (C) Open-fraction distributions for the seven transmembrane gateway interfaces across the clean-v1 cohort. (D) Included versus held-back systems with major exclusion categories, accompanied by a reduced-trajectory integrity callout summarizing the PBC audit outcome. The figure shows broad annotation coverage together with bounded, explicitly reported QC caveats; biological interpretation of the gateway annotations is outside the scope of this Data Descriptor."):
        "Figure 4. QC and completeness summary of the CoupledMD clean-v1 release. (A) Derived TM-gateway open-fraction annotations across 208 systems, grouped by G-protein family for organizational convenience; family-resolved differences in panel A are not interpreted here. (B) Orthosteric-pocket recovery rate by G-protein family, shown as a compact structural-fidelity benchmark for the derived pocket layer. (C) Open-fraction distributions for the seven transmembrane gateway interfaces across the clean-v1 cohort. (D) Included versus held-back systems with major exclusion categories, accompanied by a reduced-trajectory integrity callout summarizing the PBC audit outcome. The figure documents broad derived-record coverage together with explicitly reported QC caveats; biological interpretation of the gateway annotations is outside the scope of this Data Descriptor.",
    norm("Figure 5. Pocket-atlas annotations distributed with CoupledMD. This figure was built to show what readers can do with the pocket layer after technical validation. (A) Reserved slot for a representative structural or portal-facing snapshot in the final composed figure. (B) Consensus druggable pocket clusters mapped by receptor coverage and mean occupancy, with point size reflecting cluster volume and color indicating anatomical zone. (C) Cluster-member counts by anatomical zone. (D) Reusable GPCRdb-position anchors appearing most frequently in orthosteric and druggable cluster cores. (E) Orthosteric recovery by family as a validation view for the pocket layer. (F) High-scoring drug-design nomination examples with representative receptors. The figure shows how the atlas can support cross-receptor annotation joins, prioritization and benchmarking, while pocket clusters and proxy scores remain derived annotations rather than experimental druggability validation."):
        "Figure 5. Pocket-atlas annotations distributed with CoupledMD. (A) Reserved slot for a representative structural or portal-facing snapshot in the final composed figure. (B) Consensus druggable pocket clusters mapped by receptor coverage and mean occupancy, with point size reflecting cluster volume and color indicating anatomical zone. (C) Cluster-member counts by anatomical zone. (D) Reusable GPCRdb-position anchors appearing most frequently in orthosteric and druggable cluster cores. (E) Orthosteric recovery by family as a validation view for the pocket layer. (F) High-scoring drug-design nomination examples with representative receptors. The figure shows how the atlas can support cross-receptor annotation joins and prioritization workflows while remaining a derived annotation layer rather than experimental druggability validation.",
}


SI_REPLACEMENTS = {
    norm("Supplementary Figure S1. Receptor-level coupling-topology dendrogram. This figure was included to extend the cohort-composition story from Figure 1 to the receptor level. The circular dendrogram clusters the 174 clean-v1 receptors by presence or absence across the four major G-protein families, highlights multi-family receptors with distinct coloring, and labels each leaf with a representative four-letter PDB identifier. The main implication is that readers can quickly identify which receptors contribute most strongly to within-receptor comparative reuse, without treating dendrogram proximity as mechanistic similarity."):
        "Supplementary Figure S1. Receptor-level coupling-topology dendrogram. This figure extends the cohort-composition story from Figure 1 to the receptor level. The circular dendrogram clusters the 174 clean-v1 receptors by presence or absence across the four major G-protein families, highlights multi-family receptors, and labels each leaf with a representative four-letter PDB identifier. The implication is that readers can quickly identify receptors most relevant for within-receptor comparative reuse without treating dendrogram proximity as mechanistic similarity.",
    norm("Supplementary Figure S2. Portal, archive and API coverage. This figure was designed to document the operational completeness of the access layers. Panel A reports portal-file availability by record type, panel B compares the size of the production archive with the portal/API layer, and panel C groups the documented REST endpoints by manuscript-relevant use category. Together these results show that the archive remains the dominant long-term data product, while the portal and API provide a lighter but substantial access surface for browsing, visualization and programmatic retrieval."):
        "Supplementary Figure S2. Portal, archive and API coverage. This figure documents the operational completeness of the access layers. Panel A reports portal-file availability by record type, panel B compares the size of the production archive with the portal/API layer, and panel C groups the documented REST endpoints by manuscript-relevant use category. Together these results show that the archive remains the dominant long-term data product while the portal and API provide a lighter but substantial access surface.",
    norm("Supplementary Figure S3. Portal/API access workflow. This figure was included to show the practical route a reader follows when starting from the portal or API rather than from the archive. Panel A shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization and selected downloads, panel B groups the REST API layers for status/citation records, system metadata, derived records, visualization files and consensus summaries, and panel C restates the archive-first access model. The figure shows that access is reproducible and structured, but the stable archive remains the citable data record."):
        "Supplementary Figure S3. Portal/API access workflow. This figure shows the practical route a reader follows when starting from the portal or API rather than from the archive. Panel A shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization and selected downloads, panel B groups the REST API layers for status/citation records, system metadata, derived records, visualization files and consensus summaries, and panel C restates the archive-first access model. The implication is that access is reproducible and structured, but the stable archive remains the citable data record.",
    norm("The supplementary tables are provided as CSV files in the tables/ directory of the archive. Supplementary figures are provided as PDF and PNG files in scidata_figures/ where available; draft SVG files are retained only as editable source material and do not supersede the publication-grade PDF/PNG outputs."):
        "Compact summary tables and larger companion CSV data files are both provided in the tables/ directory of the archive, with the latter used for per-system and per-file resources that are too large for journal-style formatting. Supplementary figures are provided as PDF and PNG files in scidata_figures/ where available; draft SVG files are retained only as editable source material and do not supersede the publication-grade PDF/PNG outputs.",
}


SI_NOTE5_PARAGRAPHS = [
    "Supplementary Note 5. Figure generation and analysis protocols",
    "All figure panels were generated from frozen local analysis tables and server-side snapshot files stored in this workspace, rather than by manual inspection of the live website. Main-figure scripts are in manuscript_figures/new_figure1.py to new_figure5.py, supplementary-figure scripts are in manuscript_figures/new_figure_s1.py to new_figure_s3.py, and the underlying tabular inputs are in manuscript_figures/tables/. Web and API related panels use the local server snapshot under data/api/v1/ together with the manifest and endpoint inventory tables, so the manuscript figures can be reproduced from the same analysis layer used by the portal.",
    "Main Figure 1 was generated from tables/scidata_S1_included_systems_clean_v1.csv and tables/scidata_S2_held_back_systems.csv. Panel A is a class-by-family crosstab of the included systems; panels B and D aggregate systems by receptor gene to count total systems and the number of distinct G-protein-family contexts; panel C collapses ligand annotation into ligand-present versus apo or no-ligand categories; and panel E reduces the held-back reasons into broad exclusion classes for display. The figure is therefore a metadata-derived scope and reuse summary rather than a trajectory-derived analysis.",
    "Main Figure 2 was generated from tables/scidata_T2_repository_structure.csv, tables/scidata_T6_manifest_summary.csv and tables/scidata_T7_portal_file_availability_summary.csv. Panels A to C are schematic renderings of the archive tree, metadata schema and archive-first access model drawn from the frozen repository design and manifest summaries, while panel D is an intentionally schematic portal-access panel rather than a live screenshot. This figure should therefore be read as a documented data-organization diagram, not as an analysis of trajectory content.",
    "Main Figure 3 was generated from tables/scidata_T4_technical_validation_clean_v1.csv and tables/scidata_T4a_recovery_summary_clean_v1.csv. Panel A uses Gaussian kernel density estimation of best orthosteric-pocket frequency within each G-protein family and annotates the 0.85 recovery threshold together with the family-level recovery percentages. Panel B summarizes per-system pocket counts by family using the median and interquartile range with individual-system points overlaid. Panel C is a descriptive context panel with fixed comparison values encoded in the script; those external benchmark values should be rechecked before submission if the panel is retained.",
    "Main Figure 4 was generated from tables/scidata_S5_gateway_per_system_clean_v1.csv, tables/scidata_T4a_recovery_summary_clean_v1.csv, tables/scidata_S2_held_back_systems.csv, tables/scidata_T8a_viz_pbc_summary_clean_v1.csv and tables/scidata_T8b_viz_qc_flags_clean_v1.csv. Panel A is a heatmap of seven TM-interface gateway open-fraction values for all included systems grouped by G-protein family. Panel B restates the family-level orthosteric-recovery rates, panel C summarizes the same gateway measurements as cohort-wide box plots, and panel D combines held-back cohort counts with the reduced-trajectory audit callout. This figure therefore integrates annotation coverage, validation and release-control summaries from the frozen QC layer.",
    "Main Figure 5 was generated from the local server snapshot files data/api/v1/consensus/pockets_druggable.json, data/api/v1/consensus/pockets_orthosteric.json and data/api/v1/consensus/druggable_nominations.json together with tables/scidata_T4a_recovery_summary_clean_v1.csv. Consensus druggable clusters are summarized by receptor coverage, mean occupancy, zone assignment, voxel count and recurrent GPCRdb generic numbers; nomination examples are taken from the proxy-ranking table in the server snapshot. Panel A is currently a reserved slot for a final structural or portal-facing illustration and is not data-derived in the present draft.",
    "Supplementary Figure S1 was generated from tables/scidata_S1_included_systems_clean_v1.csv. Each receptor was encoded as a four-element presence or absence vector over Gi/o, Gs, Gq/11 and G12/13, pairwise receptor distances were computed with the Jaccard metric, and clustering used average linkage. The tree was then rendered as a circular dendrogram and each leaf was labeled with a representative PDB identifier chosen deterministically from the receptor's primary family context.",
    "Supplementary Figure S2 was generated from tables/scidata_T7_portal_file_availability_summary.csv, tables/scidata_S8_archive_manifest_clean_v1_from_metadata.csv, tables/scidata_S9_portal_file_manifest_clean_v1.csv and tables/scidata_S6_portal_api_endpoints.csv. Panel A summarizes present versus missing portal-facing records by type, panel B compares the total byte size of the archive and the portal/API layer after summing file sizes from the two manifests, and panel C groups endpoints by use category based on the manuscript_use field. All three panels are therefore derived from the local server and manifest snapshot rather than from a browser capture.",
    "Supplementary Figure S3 was generated by manuscript_figures/new_figure_s3.py as a self-contained SVG workflow figure. The panel content is schematic but is grounded in the local API organization used elsewhere in the manuscript, including status or citation routes, system metadata routes, derived-record routes and visualization routes. No live network requests are required to rebuild this figure.",
]


SI_TABLE_SECTION = [
    "Supplementary Tables",
    "Only compact summary resources are retained below as supplementary tables in the manuscript narrative. Larger per-system and per-file resources are better presented as companion CSV data files in tables/ and are listed separately so that no formatted supplementary table exceeds about 50 rows.",
    "Companion CSV data files (>50 rows; not formatted as journal tables)",
    "Companion CSV File S1. Included clean-v1 systems (208 rows). Per-system metadata for the 208 systems included in the clean-v1 release. Fields include system identifier, PDB identifier, receptor name, UniProt accession, receptor gene where available, GPCR class, G-protein family, Gα-subtype, ligand fields, replica count, per-replica length, aggregate sampling, force-field and protocol annotation, lipid composition, structural provenance, trajectory type, file-existence fields, checksum fields where available, and notes.",
    "Source file: tables/scidata_S1_included_systems_clean_v1.csv",
    "Companion CSV File S4. Per-system pocket summary (208 rows). Per-system summary of pocket outputs in the clean-v1 release. The file records pocket-output availability and pocket-derived summary fields used for technical validation and reuse. Pocket records are derived annotations and are not experimental druggability validation.",
    "Source file: tables/scidata_S4_per_system_pockets_clean_v1.csv",
    "Companion CSV File S5. Per-system gateway summary (208 rows). Per-system summary of derived gateway annotation records. These fields are provided as reusable annotations. Biological interpretation of family-resolved gateway differences is outside the scope of Paper 1.",
    "Source file: tables/scidata_S5_gateway_per_system_clean_v1.csv",
    "Companion CSV File S8. Clean-v1 archive manifest from metadata (650 rows). Metadata-derived archive manifest for the 208 clean-v1 systems. The file lists production trajectory, topology and available full-system or protein-only trajectory paths as represented in the current metadata. Final archive-level file sizes and SHA-256 checksums are synchronized with the frozen archive record at submission.",
    "Source file: tables/scidata_S8_archive_manifest_clean_v1_from_metadata.csv",
    "Companion CSV File S9. Clean-v1 portal file manifest (2,080 rows). Current server-side manifest for reduced visualization files, API JSON records, pocket grids, chain-role files and contact files across the 208 clean-v1 systems. Small text and API records include SHA-256 checksums where computed; binary or large-file checksum fields are tracked for archive completion.",
    "Source file: tables/scidata_S9_portal_file_manifest_clean_v1.csv",
    "Companion CSV File S10. Per-system pocket and orthosteric-site recovery benchmark (208 rows). Per-system technical-validation table used to evaluate pocket-output availability, orthosteric-pocket recovery, best orthosteric-pocket frequency, orthosteric-pocket count, ligand annotation and structural provenance.",
    "Source file: tables/scidata_T4_technical_validation_clean_v1.csv",
    "Companion CSV File S15. Reduced-trajectory PBC audit (208 rows). Per-system reduced-trajectory PBC and visualization audit. Fields include audit status, reduced-trajectory frame count, atom-count agreement, box agreement, checked-frame PBC flags and warning fields. These records validate the reduced visualization tier and are distinguished from final full-production archive checksums.",
    "Source file: tables/scidata_T8_viz_pbc_full_audit_clean_v1.csv",
    "Supplementary summary tables (50 rows or fewer)",
    "Supplementary Table S2. Held-back systems. Systems excluded from the clean-v1 release, with receptor and G-protein metadata, simulation metadata, structural provenance, hold reason, rerun or verification status and notes. Held-back systems are excluded from the 208-system clean-v1 counts and aggregate sampling.",
    "Source file: tables/scidata_S2_held_back_systems.csv",
    "Supplementary Table S3. File manifest and checksum checklist. Checklist of file-manifest and checksum fields required for the final archive record. The checklist defines expected fields for paths, file roles, sizes, checksums, system identifiers, replica identifiers and format descriptions; it is intended to support assembly of the final per-file archive manifest.",
    "Source file: tables/scidata_S3_file_manifest_checksum_checklist.csv",
    "Supplementary Table S6. Portal/API endpoint inventory. Inventory of REST API endpoints detected from the deployed OpenAPI schema. Endpoints are grouped by manuscript use, including citation and reuse metadata, system browsing, per-system records, visualization files, pocket records, gateway records, G-protein records and consensus summaries.",
    "Source file: tables/scidata_S6_portal_api_endpoints.csv",
    "Supplementary Table S7. Portal feature and access checklist. Checklist of portal features and access-layer items relevant to Scientific Data submission. The table records support for search, filtering, per-system metadata, visualization, downloads, API documentation, citation metadata and archive-linking features.",
    "Source file: tables/scidata_S7_website_feature_checklist.csv",
    "Supplementary Table S11. Family-level pocket recovery summary. Family-level summary of clean-v1 pocket-output availability and orthosteric-site recovery. Reports the system count, systems with pockets, recovered systems, recovery rate and mean best orthosteric-pocket frequency for Gi/o, Gs, Gq/11, G12/13 and the full clean-v1 cohort.",
    "Source file: tables/scidata_T4a_recovery_summary_clean_v1.csv",
    "Supplementary Table S12. Metadata-level clean-v1 QC summary. Metadata-level QC summary for the clean-v1 release. Records the designed systems, clean-v1 inclusion gate, 3 × 500 ns metadata gate, trajectory-path presence, topology-path presence and pocket-output availability.",
    "Source file: tables/scidata_T5_qc_summary_clean_v1.csv",
    "Supplementary Table S13. Manifest summary. Summary of archive, portal-file and OpenAPI manifest coverage, including record counts, system counts, checksum counts, checksum-pending counts and explanatory notes.",
    "Source file: tables/scidata_T6_manifest_summary.csv",
    "Supplementary Table S14. Portal file availability summary. Record-type availability summary for clean-v1 portal/API files. Reports expected systems, present records, missing records, computed checksums and pending checksums by file or record type.",
    "Source file: tables/scidata_T7_portal_file_availability_summary.csv",
    "Supplementary Table S16. Reduced-trajectory PBC audit summary. Summary of the reduced-trajectory PBC audit. The table reports 208 audited systems, 205 OK, 3 WARN, 0 hard failures, 0 atom-count mismatches, 0 blank PDB element-field issues, 0 box mismatches, 0 intra-chain break frames, 7 minor scatter frames, 0 inter-chain split frames and reduced-trajectory frame-count categories.",
    "Source file: tables/scidata_T8a_viz_pbc_summary_clean_v1.csv",
    "Supplementary Table S17. Reduced-trajectory visualization QC flags. Clean-v1 systems with minor reduced-trajectory visualization warnings or nonstandard reduced-trajectory frame counts. The flagged records are Gi_8J22, Gq_7XJL, Gs_3SN6 and Gs_7F4H.",
    "Source file: tables/scidata_T8b_viz_qc_flags_clean_v1.csv",
]


def insert_note5(doc: Document) -> None:
    anchor = find_paragraph(doc, "Supplementary Figures")
    for text in SI_NOTE5_PARAGRAPHS:
        anchor.insert_paragraph_before(text)


def rebuild_table_section(doc: Document) -> None:
    paragraphs = list(doc.paragraphs)
    start_idx = next(i for i, p in enumerate(paragraphs) if norm(p.text).startswith("Supplementary Tables"))
    end_idx = next(i for i, p in enumerate(paragraphs) if norm(p.text).startswith("Supplementary Data Availability"))
    for _ in range(end_idx - start_idx):
        remove_paragraph(doc.paragraphs[start_idx])
    end = find_paragraph(doc, "Supplementary Data Availability")
    for text in SI_TABLE_SECTION:
        end.insert_paragraph_before(text)


def clone_doc(src: Path, dst: Path) -> Document:
    shutil.copy2(src, dst)
    return Document(dst)


def main() -> None:
    m_src = HERE / "manuscript_v4.docx"
    s_src = HERE / "si_v4.docx"
    m_dst = HERE / "manuscript_v5.docx"
    s_dst = HERE / "si_v5.docx"

    m_doc = clone_doc(m_src, m_dst)
    m_count = replace_paragraphs(m_doc, MANUSCRIPT_REPLACEMENTS)
    m_doc.save(m_dst)

    s_doc = clone_doc(s_src, s_dst)
    s_count = replace_paragraphs(s_doc, SI_REPLACEMENTS)
    insert_note5(s_doc)
    rebuild_table_section(s_doc)
    s_doc.save(s_dst)

    print(f"{m_dst}: updated {m_count} paragraphs")
    print(f"{s_dst}: updated {s_count} figure paragraphs, inserted Note 5 and rebuilt table section")


if __name__ == "__main__":
    main()
