#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path

from docx import Document


HERE = Path(__file__).resolve().parent


def norm(text: str) -> str:
    return " ".join(text.split())


MANUSCRIPT_REPLACEMENTS = {
    norm("Figure 1 is intended to be read as the scope statement for the resource. Panel A quantifies the class-by-family coverage of the 208-system clean-v1 cohort. Panel B highlights the receptors represented across the largest number of systems and marks those sampled with more than one G-protein family, indicating where within-receptor comparative reuse is immediately possible without implying a coupling mechanism. Panel C separates ligand-present and apo or no-ligand systems by family so that users can identify ligand-aware and ligand-independent subsets. Panel D expands this reuse view to the 42 most represented receptors, where larger and accent-colored markers identify receptors sampled across multiple G-protein-family contexts. Panel E keeps the release boundary explicit by contrasting the 208 included systems with the 14 held-back systems and by grouping the held-back records into nonstandard-length or missing/incomplete-output categories."):
        "Figure 1 serves as the entry-point figure for the dataset, so its purpose is to show what is in clean-v1 and where direct comparative reuse is possible. We therefore organized the figure to move from overall cohort composition to receptor-level reuse potential: panel A quantifies class-by-family coverage across the 208 included systems, panels B and D show that a smaller but important subset of receptors appears in more than one G-protein-family context, panel C separates ligand-present from apo or no-ligand systems, and panel E keeps the 208-included and 14-held-back boundary explicit. The main implication is that CoupledMD is broad enough for cross-family benchmarking and within-receptor comparisons, but still curated enough that readers can see exactly which systems define the release and which records remain outside it.",
    norm("Figure 2 describes how a user should navigate the data product. Panel A organizes the archive into manifest, metadata, per-system topology, trajectory, reduced-trajectory, feature, pocket, QC, code and web/API snapshot components. Panel B maps the same organization onto the per-system metadata fields, linking receptor, G-protein, ligand/state, replica and file/QC information. Panel C makes the access hierarchy explicit: the archive is the stable record for citation and reproducibility, whereas the portal and API are access layers. Panel D translates that hierarchy into a publication-ready portal-access schematic showing search, filtering, structure viewing, download actions and API entry points, so the figure remains interpretable even before a final live screenshot is inserted."):
        "Figure 2 is included to explain how the data product is organized and how a reader should move through it. We therefore show the archive hierarchy in panel A, the per-system metadata logic in panel B, the archive-first access relationship in panel C, and the practical portal/API route in panel D through search, filters, structure viewing, download actions and API entry points. The figure makes clear that CoupledMD is not only a collection of trajectories but a structured resource with a stable archival core and lighter access layers, which is important for readers deciding whether they need reproducible archive files, processed metadata, or rapid web-based inspection.",
    norm("Together, Figure 3A and 3B provide the main technical-validation view for pocket-derived records. The recovery panel asks whether known ligand-accessible receptor pockets are recovered at the expected location often enough to support reuse of the pocket annotations. The pocket-count panel asks whether the pocket-detection layer produces a plausible and trackable number of records per system rather than sparse or unstable outputs. Figure 3C then places CoupledMD beside a single-receptor GPCR trajectory resource and a large general-protein MD resource to contextualize the niche that this release occupies: fewer systems than domain-scale repositories, but unusually broad sampling for membrane-embedded GPCR/G-protein complexes. This comparison is descriptive and is not used as a quality benchmark."):
        "Figure 3 provides the main technical-validation argument for the pocket layer and also situates the scale of the release. We use panel A to ask whether known orthosteric sites are recovered often enough to trust the derived pocket annotations, and the result is positive: orthosteric-pocket recovery at the 0.85 threshold is observed in 156 of 206 systems with pocket outputs, with family-level rates of 72.5% for Gi/o, 76.1% for Gs, 83.3% for Gq/11 and 66.7% for G12/13. Panel B shows that the pocket-detection layer is not trivially sparse, with median pocket counts of 10 to 11 per system across the major families, while panel C places CoupledMD in the practical niche between single-target GPCR resources and very large general-protein MD repositories. The implication is that readers can treat the pocket layer as a technically validated reuse feature and can also see why this dataset is distinctive: it emphasizes breadth across active GPCR/G-protein complexes rather than maximal scale alone.",
    norm("Figure 4 is the release-integrity figure. Panel A catalogs derived TM-gateway open-fraction annotations across the 208 systems as machine-readable records, with family grouping used only to organize the display. Panel B restates family-level orthosteric-pocket recovery rates as a compact structural-fidelity benchmark for the derived pocket layer. Panel C summarizes the open-fraction distributions for the seven transmembrane gateway interfaces across the full cohort, showing that the gateway layer spans a broad dynamic range rather than collapsing to a single trivial state. Panel D connects these annotation summaries to the transparent release boundary by contrasting the 208 included systems with the 14 held-back systems and by reporting the reduced-trajectory integrity outcome as a compact callout. These panels document completeness and annotation behavior; they are not used to infer biological differences among G-protein families."):
        "Figure 4 is the release-integrity figure, and its purpose is to show that the annotation and reduced-visualization layers are broad, checkable and transparent rather than merely appended to the archive. Panel A shows that TM-gateway open-fraction annotations are available across all 208 included systems, panel B restates the family-level orthosteric-recovery rates as a compact structural-fidelity benchmark, panel C shows that the seven gateway interfaces span a nontrivial range of open-fraction values across the cohort, and panel D links those derived records back to release control by contrasting the 208 included systems with the 14 held-back systems while also reporting the reduced-trajectory audit outcome of 205 OK systems, 3 WARN systems and 0 hard failures. The implication is that the distributed annotation and visualization tiers are usable at scale, with known caveats clearly bounded and reported rather than hidden.",
    norm("Figure 5 describes the pocket-annotation layer as a reusable data product. Panel A is reserved for a representative structural or portal-facing snapshot during final layout. Panel B maps consensus druggable pocket clusters by receptor coverage and mean occupancy, with marker size reflecting cluster volume and color indicating anatomical zone. Panel C counts cluster members across orthosteric, transmembrane-core allosteric, intracellular-allosteric and related zones. Panel D lists the GPCRdb generic positions that recur most often in the orthosteric and druggable cluster cores, allowing residue-level joins across receptors without relying only on receptor-specific numbering. Panel E restates family-level orthosteric recovery as a validation view for the distributed pocket records, and Panel F highlights nomination examples with the highest proxy scores together with example receptors. These outputs can support prioritization or benchmarking workflows, but the manuscript does not treat them as experimental druggability validation or as mechanistic discoveries."):
        "Figure 5 is designed to show why the pocket layer is useful beyond simple validation and why it can function as a reusable atlas. Panel B shows that the consensus druggable clusters differ in both receptor coverage and mean occupancy, panel C groups those clusters into anatomical zones, panel D identifies the GPCRdb generic positions that recur most often in orthosteric and druggable cluster cores, panel E keeps the family-level orthosteric-recovery benchmark visible, and panel F highlights nomination examples with high proxy scores and representative receptors; panel A is reserved for a final structural or portal-facing snapshot to visually anchor the atlas. The main implication is that readers can use these records for cross-receptor joins, prioritization and benchmarking workflows, while still understanding that the atlas is a derived annotation layer rather than direct experimental evidence of druggability.",
    norm("Figure 1. Coverage and reuse landscape of the CoupledMD clean-v1 release. (A) Class × G-protein-family coverage across 208 systems. (B) Receptors represented across the largest number of systems, with multi-family receptors highlighted as direct within-receptor reuse opportunities. (C) Ligand-present versus apo or no-ligand systems by family. (D) Receptor reuse landscape for the most represented receptors, with accent-colored larger markers denoting receptors sampled across more than one G-protein family. (E) Release boundary: 208 included and 14 held back from 222 designed systems, with held-back records grouped into major exclusion categories. Composition is shown for resource description; biological interpretation of family or ligand patterns is outside the scope of this Data Descriptor."):
        "Figure 1. Coverage and reuse landscape of the CoupledMD clean-v1 release. This figure was constructed to define the scope of the release and the immediate reuse opportunities. (A) Class × G-protein-family coverage across 208 systems. (B) Receptors represented across the largest number of systems, with multi-family receptors highlighted as direct within-receptor reuse opportunities. (C) Ligand-present versus apo or no-ligand systems by family. (D) Receptor reuse landscape for the most represented receptors, with accent-colored larger markers denoting receptors sampled across more than one G-protein family. (E) Release boundary: 208 included and 14 held back from 222 designed systems, with held-back records grouped into major exclusion categories. The figure shows that the release combines broad coverage with transparent cohort definition; biological interpretation of family or ligand patterns is outside the scope of this Data Descriptor.",
    norm("Figure 2. Repository organization, metadata schema and three-tier access model of CoupledMD. (A) Archive hierarchy, including manifest, metadata, systems, topology, trajectories, reduced files, features, pocket records, QC records, code and web/API snapshots. (B) Per-system metadata schema for system, receptor, G protein, ligand/state, replicas, files and QC status. (C) Archive-first access model: the stable archive is the citable record, while the web portal and REST API provide browse, visualization and programmatic access. (D) Portal-access schematic showing search, filters, structure viewing, download actions and API entry points. File formats and field definitions are detailed in Tables 2 and 3."):
        "Figure 2. Repository organization, metadata schema and three-tier access model of CoupledMD. This figure explains how the resource is structured and accessed. (A) Archive hierarchy, including manifest, metadata, systems, topology, trajectories, reduced files, features, pocket records, QC records, code and web/API snapshots. (B) Per-system metadata schema for system, receptor, G protein, ligand/state, replicas, files and QC status. (C) Archive-first access model: the stable archive is the citable record, while the web portal and REST API provide browse, visualization and programmatic access. (D) Portal-access schematic showing search, filters, structure viewing, download actions and API entry points. The figure shows that full reproducibility depends on the archive, whereas the portal and API are optimized access layers. File formats and field definitions are detailed in Tables 2 and 3.",
    norm("Figure 3. Technical validation and dataset-scope context for the CoupledMD clean-v1 release. (A) Best per-system orthosteric-pocket frequency by G-protein family; the dashed line marks the 0.85 recovery threshold and recovery percentages are annotated by family. (B) Per-system pocket-count distribution by family, summarized as median and interquartile range with individual-system points overlaid. (C) Descriptive comparison of system count and aggregate sampling against representative single-receptor GPCR and general-protein MD resources to contextualize the scope of CoupledMD. Validation is technical and does not interpret biological mechanism."):
        "Figure 3. Technical validation and dataset-scope context for the CoupledMD clean-v1 release. This figure was designed to test the pocket layer and to place the dataset in context. (A) Best per-system orthosteric-pocket frequency by G-protein family; the dashed line marks the 0.85 recovery threshold and recovery percentages are annotated by family. (B) Per-system pocket-count distribution by family, summarized as median and interquartile range with individual-system points overlaid. (C) Descriptive comparison of system count and aggregate sampling against representative single-receptor GPCR and general-protein MD resources to contextualize the scope of CoupledMD. The results support technical reuse of the derived pocket records while showing that CoupledMD occupies a distinct middle ground between narrow single-target resources and much larger general MD repositories.",
    norm("Figure 4. QC and completeness summary of the CoupledMD clean-v1 release. (A) Derived TM-gateway open-fraction annotations across 208 systems, grouped by G-protein family for organizational convenience; family-resolved differences in panel A are not interpreted here. (B) Orthosteric-pocket recovery rate by G-protein family, shown as a compact structural-fidelity benchmark for the derived pocket layer. (C) Open-fraction distributions for the seven transmembrane gateway interfaces across the clean-v1 cohort. (D) Included versus held-back systems with major exclusion categories, accompanied by a reduced-trajectory integrity callout summarizing the PBC audit outcome. Biological interpretation of the gateway annotations is outside the scope of this Data Descriptor."):
        "Figure 4. QC and completeness summary of the CoupledMD clean-v1 release. This figure was assembled to show that the derived annotation and reduced-trajectory layers are complete enough for practical reuse and honest enough about remaining caveats. (A) Derived TM-gateway open-fraction annotations across 208 systems, grouped by G-protein family for organizational convenience; family-resolved differences in panel A are not interpreted here. (B) Orthosteric-pocket recovery rate by G-protein family, shown as a compact structural-fidelity benchmark for the derived pocket layer. (C) Open-fraction distributions for the seven transmembrane gateway interfaces across the clean-v1 cohort. (D) Included versus held-back systems with major exclusion categories, accompanied by a reduced-trajectory integrity callout summarizing the PBC audit outcome. The figure shows broad annotation coverage together with bounded, explicitly reported QC caveats; biological interpretation of the gateway annotations is outside the scope of this Data Descriptor.",
    norm("Figure 5. Pocket-atlas annotations distributed with CoupledMD. (A) Reserved slot for a representative structural or portal-facing snapshot in the final composed figure. (B) Consensus druggable pocket clusters mapped by receptor coverage and mean occupancy, with point size reflecting cluster volume and color indicating anatomical zone. (C) Cluster-member counts by anatomical zone. (D) Reusable GPCRdb-position anchors appearing most frequently in orthosteric and druggable cluster cores. (E) Orthosteric recovery by family as a validation view for the pocket layer. (F) High-scoring drug-design nomination examples with representative receptors. Pocket clusters and proxy scores are derived annotations and are not experimental druggability validation; biological or pharmacological interpretation is outside the scope of this Data Descriptor."):
        "Figure 5. Pocket-atlas annotations distributed with CoupledMD. This figure was built to show what readers can do with the pocket layer after technical validation. (A) Reserved slot for a representative structural or portal-facing snapshot in the final composed figure. (B) Consensus druggable pocket clusters mapped by receptor coverage and mean occupancy, with point size reflecting cluster volume and color indicating anatomical zone. (C) Cluster-member counts by anatomical zone. (D) Reusable GPCRdb-position anchors appearing most frequently in orthosteric and druggable cluster cores. (E) Orthosteric recovery by family as a validation view for the pocket layer. (F) High-scoring drug-design nomination examples with representative receptors. The figure shows how the atlas can support cross-receptor annotation joins, prioritization and benchmarking, while pocket clusters and proxy scores remain derived annotations rather than experimental druggability validation.",
}


SI_REPLACEMENTS = {
    norm("Supplementary Figure S1. Receptor-level coupling-topology dendrogram. Circular dendrogram of the 174 clean-v1 receptors clustered by presence or absence across the four major G-protein families. Leaf ticks are colored by single-family assignment or by multi-family representation, and each leaf is labeled by a representative four-letter PDB identifier. The figure provides receptor-level coupling-topology context for Figure 1 without implying mechanistic similarity among clustered receptors."):
        "Supplementary Figure S1. Receptor-level coupling-topology dendrogram. This figure was included to extend the cohort-composition story from Figure 1 to the receptor level. The circular dendrogram clusters the 174 clean-v1 receptors by presence or absence across the four major G-protein families, highlights multi-family receptors with distinct coloring, and labels each leaf with a representative four-letter PDB identifier. The main implication is that readers can quickly identify which receptors contribute most strongly to within-receptor comparative reuse, without treating dendrogram proximity as mechanistic similarity.",
    norm("Supplementary Figure S2. Portal, archive and API coverage. Summary of archive, portal and API coverage for the clean-v1 release. Panel A reports portal-file availability by record type, Panel B compares the size of the production archive with the portal/API layer, and Panel C groups the documented REST endpoints by manuscript-relevant use category. The figure supports the Data Records and Usage Notes sections by documenting how operational coverage is distributed across the archive and access layers."):
        "Supplementary Figure S2. Portal, archive and API coverage. This figure was designed to document the operational completeness of the access layers. Panel A reports portal-file availability by record type, panel B compares the size of the production archive with the portal/API layer, and panel C groups the documented REST endpoints by manuscript-relevant use category. Together these results show that the archive remains the dominant long-term data product, while the portal and API provide a lighter but substantial access surface for browsing, visualization and programmatic retrieval.",
    norm("Supplementary Figure S3. Portal/API access workflow. Workflow for interactive and programmatic access to CoupledMD. Panel A shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization and selected downloads, Panel B groups the REST API layers for status/citation records, system metadata, derived records, visualization files and consensus summaries, and Panel C restates the archive-first access model. The stable archive remains the citable data record."):
        "Supplementary Figure S3. Portal/API access workflow. This figure was included to show the practical route a reader follows when starting from the portal or API rather than from the archive. Panel A shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization and selected downloads, panel B groups the REST API layers for status/citation records, system metadata, derived records, visualization files and consensus summaries, and panel C restates the archive-first access model. The figure shows that access is reproducible and structured, but the stable archive remains the citable data record.",
}


def patch_doc(doc: Document, replacements: dict[str, str]) -> int:
    count = 0
    for p in doc.paragraphs:
        key = norm(p.text)
        if key in replacements:
            p.text = replacements[key]
            count += 1
    return count


def clone_and_patch(src: Path, dst: Path, replacements: dict[str, str]) -> int:
    shutil.copy2(src, dst)
    doc = Document(dst)
    count = patch_doc(doc, replacements)
    doc.save(dst)
    return count


def main() -> None:
    out1 = HERE / "manuscript_v4.docx"
    out2 = HERE / "si_v4.docx"
    n1 = clone_and_patch(HERE / "manuscript_v3.docx", out1, MANUSCRIPT_REPLACEMENTS)
    n2 = clone_and_patch(HERE / "si_v3.docx", out2, SI_REPLACEMENTS)
    print(f"{out1}: updated {n1} paragraphs")
    print(f"{out2}: updated {n2} paragraphs")


if __name__ == "__main__":
    main()
