#!/usr/bin/env python3
"""
assemble_tables.py  — Phase 4.1: embed T1-T3 in main text + build SI S1-S8

Produces (all under versions/):
  manuscript_v1.4.1.docx           — main text + figures + T1-T3 embedded
  SI_v1.0.0.docx                   — standalone SI with S1-S8
  manuscript_v1.4.1_combined.docx  — main + T1-T3 + SI appended after References

Also writes:
  COMPILE_CHECK.md                 — assertion report

Usage:
  python assemble_tables.py
"""

import csv
import glob
import re
import shutil
from pathlib import Path

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

HERE = Path(__file__).resolve().parent
FIGDIR  = HERE / "figures"
TABDIR  = HERE / "tables"
P1DIR   = HERE / "phase1_outputs"
VERSIONS = HERE / "versions"
VERSIONS.mkdir(exist_ok=True)
MD_SRC = HERE / "nar_manuscript.md"

FIGFILES = {
    1: (FIGDIR / "figure_1.png",                    6.5),
    2: (FIGDIR / "figure_2.png",                    3.3),
    3: (FIGDIR / "figure_3.png",                    6.5),
    4: (FIGDIR / "figure4_gprotein_interface.png",  6.5),
    5: (FIGDIR / "figure5_partner_switching.png",   6.5),
}

INK         = RGBColor(0x17, 0x1b, 0x22)
GRAY_HEADER = RGBColor(0xD9, 0xD9, 0xD9)
GRAY_LIGHT  = RGBColor(0xF2, 0xF2, 0xF2)

# ── table metadata ────────────────────────────────────────────────────────────

TABLE_META = {
    "T1": {
        "file":    TABDIR / "T1_cohort_summary.csv",
        "caption": ("Table T1. CoupledMD cohort summary by G-protein subfamily."
                    " Systems count, structural provenance, unique receptors, and aggregate"
                    " MD sampling per G-protein subfamily."),
        "col_widths": [1.0, 0.8, 0.9, 1.1, 1.0, 0.9, 0.8],
    },
    "T2": {
        "file":    TABDIR / "T2_recovery_benchmark.csv",
        "caption": ("Table T2. Orthosteric binding-site recovery benchmark across the"
                    " 209 CoupledMD systems with detectable pockets."
                    " Recovery rate = fraction of pocket-having systems where the fpocket"
                    " consensus pocket overlaps the orthosteric site."),
        "col_widths": [1.5, 0.9, 1.1, 1.1, 1.1, 1.1],
    },
    "T3": {
        "file":    TABDIR / "T3_partner_switching.csv",
        "caption": ("Table T3. Partner-switching census: all 16 receptor contrasts with"
                    " MD data for two or more G-protein partners."
                    " Jaccard similarity = |A∩B|/|A∪B| over consensus-pocket cluster sets;"
                    " gateway dist. = mean |Δ open fraction| across all seven TM portal pairs."
                    " Bootstrap 95% CIs derived from per-replica portal-pair distributions."
                    " Full data in T3_partner_switching.csv."),
        # display columns (subset for readability): indices into T3
        "display_cols": [0, 1, 7, 8, 9, 10, 11, 12],
        "display_headers": [
            "Receptor", "Contrast",
            "Jaccard sim.", "Gateway dist.",
            "CI low", "CI high",
            "α5 tilt diff. (°)", "Note"
        ],
        "col_widths": [0.7, 0.65, 0.7, 0.75, 0.5, 0.5, 0.85, 0.85],
    },
    "S1": {
        "file":    TABDIR / "S1_system_inventory.csv",
        "caption": ("Table S1. Complete 222-system inventory."
                    " Source: systems_master.csv + pocket/gateway data availability flags."
                    " Gi_8HK2 shows length_per_replica_ns = 2 — flagged as possible"
                    " data-entry error; see notes column. All other systems: 500 ns/replica."
                    " Full 19-column table in S1_system_inventory.csv."),
        # show 10 of 19 columns
        "display_cols": [0, 1, 2, 5, 6, 9, 10, 11, 14, 18],
        "display_headers": [
            "System ID", "PDB ID", "Receptor name",
            "G-protein family", "G-alpha subtype",
            "Replicas", "Length/replica (ns)", "Total sampling (ns)",
            "Provenance", "Notes"
        ],
        "col_widths": [0.85, 0.55, 1.3, 0.75, 1.0, 0.5, 0.8, 0.8, 0.7, 1.1],
        "font_size": 7,
    },
    "S2": {
        "file":    TABDIR / "S2_druggable_pocket_clusters.csv",
        "caption": ("Table S2. All 50 druggable consensus pocket clusters."
                    " Generated by consensus clustering of fpocket outputs across 209 systems;"
                    " mean occupancy frequency averaged across member systems and replicas."
                    " Core generic positions truncated to 50 characters; full list in CSV."),
        "display_cols": [0, 1, 2, 3, 4, 6, 7, 8, 9],
        "display_headers": [
            "Cluster ID", "Members (n)", "Unique pockets (n)",
            "Mean freq.", "Zone(s)",
            "Gi/o (n)", "Gs (n)", "Gq/11 (n)", "G12/13 (n)"
        ],
        "col_widths": [0.6, 0.7, 0.8, 0.65, 1.4, 0.55, 0.5, 0.55, 0.6],
        "font_size": 8,
    },
    "S3": {
        "file":    TABDIR / "S3_alpha5_geometry.csv",
        "caption": ("Table S3. G-protein α5 helix coupling geometry for the 27-system"
                    " pilot cohort. Tilt angle (°), insertion depth (Å), buried SASA (Å²),"
                    " and hook angle (°) extracted per system; composite rank integrates"
                    " all four descriptors."),
        "col_widths": [0.55, 0.9, 0.75, 0.75, 0.75, 0.85, 0.9],
        "font_size": 8,
    },
    "S4": {
        "file":    TABDIR / "S4_partner_switching_pocket_detail.csv",
        "caption": ("Table S4. Per-pocket pocket-switching detail for all 16 receptor"
                    " contrasts. sign = +1 pocket gained under Partner A, −1 lost."
                    " zones: GPCRdb zone membership; core: generic positions of pocket core."),
        "col_widths": [0.7, 0.65, 0.6, 0.5, 0.45, 0.5, 0.45, 1.0, 1.4, 0.5],
        "font_size": 7,
    },
    "S5": {
        "file":    TABDIR / "S5_gateway_per_system.csv",
        "caption": ("Table S5. Per-system transmembrane gateway open fractions for all"
                    " seven portal pairs. Values = mean open fraction across 3 replicas;"
                    " 95% CIs in brackets. Only open_fraction columns shown here; full 22-column"
                    " table (including mean distances and per-CI bounds) in S5_gateway_per_system.csv."),
        # display cols: System ID + one open_fraction per portal (cols 0,1,4,7,10,13,16,19)
        "display_cols": [0, 1, 4, 7, 10, 13, 16, 19],
        "display_headers": [
            "System ID",
            "TM3-TM4 open_frac", "TM7-TM1 open_frac",
            "TM4-TM5 open_frac", "TM5-TM6 open_frac",
            "TM1-TM2 open_frac", "TM6-TM7 open_frac",
            "TM2-TM3 open_frac"
        ],
        "col_widths": [0.85, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8],
        "font_size": 7,
    },
    "S6": {
        "file":    TABDIR / "S6_per_system_pockets.csv",
        "caption": ("Table S6. Per-system consensus pocket membership summary."
                    " Druggable and orthosteric cluster IDs assigned to each of 222 systems."),
        "col_widths": [0.85, 1.3, 0.8, 1.1, 0.6, 1.2, 1.2, 0.6],
        "font_size": 8,
    },
    "S7": {
        "file":    None,
        "caption": ("Table S7. GPCRdb / Flock-GproteinDB coupling selectivity cross-reference."
                    " [DEFERRED — data not yet available]."
                    " Planned content: GPCRdb primary coupling annotation, Flock selectivity-"
                    "determining position list, and known approved-ligand cross-reference for"
                    " all 222 CoupledMD systems. Will be added when coupling annotation"
                    " pipeline completes."),
        "deferred": True,
    },
    "S8": {
        "file":    P1DIR / "recovery_benchmark.csv",
        "caption": ("Table S8. Full per-system orthosteric site recovery benchmark."
                    " Computed by phase1_analysis.py from per-system pockets.json."
                    " ortho_recovered = True if any fpocket consensus pocket overlaps"
                    " the orthosteric binding site; best_ortho_freq = highest-occupancy"
                    " orthosteric pocket frequency. Includes the 13 systems with no pockets."),
        "col_widths": [0.85, 0.7, 0.7, 0.6, 0.9, 0.9, 0.7, 0.85, 0.7],
        "font_size": 8,
    },
}


# ── CSV loader ────────────────────────────────────────────────────────────────

def load_csv(path):
    """Return (headers, rows) or (None, None) if file absent."""
    path = Path(path)
    if not path.exists():
        return None, None
    with open(path, newline="", encoding="utf-8") as f:
        reader = list(csv.reader(f))
    return reader[0], reader[1:]


# ── Word helpers ──────────────────────────────────────────────────────────────

def parse_inline(text):
    out, buf = [], ""
    bold = italic = mono = False
    i = 0
    while i < len(text):
        if text[i:i+2] == "**":
            if buf: out.append((buf, bold, italic, mono)); buf = ""
            bold = not bold; i += 2; continue
        if text[i] == "*":
            if buf: out.append((buf, bold, italic, mono)); buf = ""
            italic = not italic; i += 1; continue
        if text[i] == "`":
            if buf: out.append((buf, bold, italic, mono)); buf = ""
            mono = not mono; i += 1; continue
        buf += text[i]; i += 1
    if buf: out.append((buf, bold, italic, mono))
    return out


def add_runs(paragraph, text):
    for seg, bold, italic, mono in parse_inline(text):
        r = paragraph.add_run(seg)
        r.bold = bold; r.italic = italic
        if mono:
            r.font.name = "Consolas"; r.font.size = Pt(9)
    return paragraph


def setup_styles(doc):
    normal = doc.styles["Normal"]
    normal.font.name = "Arial"; normal.font.size = Pt(10)
    normal.font.color.rgb = INK
    pf = normal.paragraph_format
    pf.space_after = Pt(6); pf.line_spacing = 1.15
    for name, size in [("Heading 1", 13), ("Heading 2", 11), ("Title", 16)]:
        st = doc.styles[name]
        st.font.name = "Arial"; st.font.size = Pt(size)
        st.font.color.rgb = INK; st.font.bold = True


def set_cell_bg(cell, rgb):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    # RGBColor is a tuple subclass; str() returns the hex string e.g. "D9D9D9"
    hex_color = str(rgb)
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def set_cell_margins(cell, top=0.04, bottom=0.04, left=0.07, right=0.07):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcMar = OxmlElement("w:tcMar")
    for side, val in [("top", top), ("bottom", bottom),
                       ("left", left), ("right", right)]:
        m = OxmlElement(f"w:{side}")
        m.set(qn("w:w"), str(int(val * 1440)))
        m.set(qn("w:type"), "dxa")
        tcMar.append(m)
    tcPr.append(tcMar)


def add_word_table(doc, meta_key, headers, rows):
    """Build a native Word table from metadata + data. Returns (#rows, #cols) tuple."""
    meta  = TABLE_META[meta_key]
    font_size = meta.get("font_size", 9)

    # ── caption ──────────────────────────────────────────────────────────
    cap = doc.add_paragraph()
    cap.paragraph_format.space_before = Pt(10)
    cap.paragraph_format.space_after  = Pt(3)
    cap_text = meta["caption"]
    # bold the "Table Tx." label
    m = re.match(r"^(Table [TS]\d+\.)(.*)", cap_text)
    if m:
        r = cap.add_run(m.group(1)); r.bold = True; r.font.size = Pt(9)
        r2 = cap.add_run(m.group(2)); r2.font.size = Pt(9)
    else:
        r = cap.add_run(cap_text); r.font.size = Pt(9)

    # ── deferred placeholder ──────────────────────────────────────────────
    if meta.get("deferred"):
        p = doc.add_paragraph()
        r = p.add_run("[Table deferred — data not yet available. See caption for planned content.]")
        r.italic = True; r.font.size = Pt(9)
        doc.add_paragraph().paragraph_format.space_after = Pt(4)
        return (0, 0)

    # ── column selection ─────────────────────────────────────────────────
    display_cols    = meta.get("display_cols")
    display_headers = meta.get("display_headers")

    if display_cols is not None:
        show_headers = display_headers
        show_rows    = []
        for row in rows:
            # pad row to avoid index errors on short rows
            padded = row + [""] * max(0, max(display_cols) + 1 - len(row))
            show_rows.append([padded[i] for i in display_cols])
    else:
        show_headers = headers
        show_rows    = rows

    # ── build table ──────────────────────────────────────────────────────
    n_cols = len(show_headers)
    col_widths = meta.get("col_widths")
    if col_widths is None or len(col_widths) != n_cols:
        total = 6.4
        col_widths = [total / n_cols] * n_cols

    tbl = doc.add_table(rows=1 + len(show_rows), cols=n_cols)
    tbl.style = "Table Grid"

    # set column widths
    for ci in range(n_cols):
        for cell in tbl.column_cells(ci):
            cell.width = Inches(col_widths[ci])

    # header row
    hrow = tbl.rows[0]
    for ci, h in enumerate(show_headers):
        cell = hrow.cells[ci]
        set_cell_bg(cell, GRAY_HEADER)
        set_cell_margins(cell)
        p = cell.paragraphs[0]
        r = p.add_run(str(h)); r.bold = True; r.font.size = Pt(font_size)

    # data rows
    for ri, row in enumerate(show_rows):
        wrow = tbl.rows[ri + 1]
        # alternate row shading for readability on large tables
        bg = GRAY_LIGHT if (len(rows) > 20 and ri % 2 == 1) else None
        for ci, val in enumerate(row):
            cell = wrow.cells[ci]
            if bg:
                set_cell_bg(cell, bg)
            set_cell_margins(cell)
            p = cell.paragraphs[0]
            # truncate very long values in display tables
            display_val = str(val) if val not in ("", None) else "n/a"
            if len(display_val) > 120:
                display_val = display_val[:117] + "..."
            r = p.add_run(display_val); r.font.size = Pt(font_size)

    doc.add_paragraph().paragraph_format.space_after = Pt(6)
    return (len(show_rows), n_cols)


def add_figure(doc, num, caption_lines):
    path, width = FIGFILES[num]
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(8)
    p.paragraph_format.space_after  = Pt(2)
    p.add_run().add_picture(str(path), width=Inches(width))
    cap = doc.add_paragraph()
    cap.paragraph_format.space_after = Pt(10)
    first = caption_lines[0]
    m = re.match(r"^(\*\*Figure \d+\..*?\*\*)(.*)$", first)
    if m:
        add_runs(cap, m.group(1))
        if m.group(2).strip():
            add_runs(cap, " " + m.group(2).strip())
    else:
        add_runs(cap, first)
    for line in caption_lines[1:]:
        add_runs(cap, " " + line.strip())
    for run in cap.runs:
        run.font.size = Pt(9)


# ── table data loading ────────────────────────────────────────────────────────

def load_all():
    """Return dict meta_key -> (headers, rows, status_str)."""
    result = {}
    for key, meta in TABLE_META.items():
        if meta.get("deferred"):
            result[key] = (None, None, "deferred")
            continue
        fpath = meta.get("file")
        if fpath is None or not Path(fpath).exists():
            result[key] = (None, None, f"missing:{fpath}")
            continue
        h, r = load_csv(fpath)
        if h is None:
            result[key] = (None, None, f"empty:{fpath}")
        else:
            result[key] = (h, r, "ok")
    return result


# ── detection helpers ─────────────────────────────────────────────────────────

def para_inserts_table(text):
    """Return table key if this paragraph should be followed by a table, else None."""
    if "Table T1" in text:
        return "T1"
    if "Table T2" in text:
        return "T2"
    if "Table T3" in text:
        return "T3"
    return None


# ── main build ────────────────────────────────────────────────────────────────

def build_main(doc, lines, data, include_si=False):
    """
    Parse markdown and emit into doc.
    include_si=True appends the SI section after References.
    Returns dict of {table_key: (rows, cols)} for assertions.
    """
    setup_styles(doc)
    for section in doc.sections:
        section.top_margin    = Inches(0.9)
        section.bottom_margin = Inches(0.9)
        section.left_margin   = Inches(0.9)
        section.right_margin  = Inches(0.9)

    mode     = "body"
    fig_buf  = []
    fig_num  = None
    table_stats = {}    # key -> (rows, cols)
    figures_found = []

    def flush_figure():
        nonlocal fig_buf, fig_num
        if fig_num is not None and fig_buf:
            add_figure(doc, fig_num, fig_buf)
            figures_found.append(fig_num)
        fig_buf = []; fig_num = None

    for raw in lines:
        line    = raw.rstrip()
        stripped = line.strip()

        if stripped == "---":
            continue

        # headings
        if line.startswith("## "):
            title = line[3:].strip()
            low = title.lower()
            if low.startswith("figure caption"):
                flush_figure()
                mode = "figures"
                doc.add_heading("Figures", level=1)
                continue
            if low.startswith("reference"):
                flush_figure()
                mode = "references"
                doc.add_heading("References", level=1)
                continue
            flush_figure()
            mode = "body"
            doc.add_heading(title, level=1)
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=2)
            continue
        if line.startswith("# "):
            p = doc.add_paragraph(style="Title")
            add_runs(p, line[2:].strip())
            continue

        if not stripped:
            continue

        if mode == "figures":
            if stripped.startswith("**Figure"):
                flush_figure()
                fm = re.match(r"\*\*Figure (\d+)\.", stripped)
                fig_num = int(fm.group(1)) if fm else None
                fig_buf = [stripped]
            else:
                fig_buf.append(stripped)
            continue

        if mode == "references":
            p = doc.add_paragraph()
            p.paragraph_format.left_indent       = Inches(0.25)
            p.paragraph_format.first_line_indent = Inches(-0.25)
            p.paragraph_format.space_after       = Pt(3)
            add_runs(p, stripped)
            for r in p.runs: r.font.size = Pt(9)
            continue

        # ordinary body paragraph
        add_runs(doc.add_paragraph(), stripped)

        # insert table after paragraph if referenced
        tkey = para_inserts_table(stripped)
        if tkey and tkey in data:
            h, r, status = data[tkey]
            if status == "ok":
                rc = add_word_table(doc, tkey, h, r)
                table_stats[tkey] = rc
            else:
                p = doc.add_paragraph()
                p.add_run(f"[Table {tkey} — {status}]").italic = True

    flush_figure()

    # ── SI section ──────────────────────────────────────────────────────
    if include_si:
        doc.add_page_break()
        doc.add_heading("Supplementary Information", level=1)
        p = doc.add_paragraph()
        r = p.add_run(
            "CoupledMD: a uniform-protocol molecular dynamics web resource for comparative "
            "analysis of 222 GPCR–G-protein ternary complexes."
        )
        r.bold = True; r.font.size = Pt(10)
        doc.add_paragraph(
            "The following supplementary tables provide the complete per-system data "
            "underlying the analyses reported in the main text. All values are computed "
            "directly from the CoupledMD analysis pipeline; no values have been manually "
            "entered or adjusted. CSV source files are listed in each table caption."
        ).paragraph_format.space_after = Pt(10)

        for skey in ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"]:
            h, r, status = data.get(skey, (None, None, "missing"))
            if status == "ok":
                rc = add_word_table(doc, skey, h, r)
                table_stats[skey] = rc
            else:
                # deferred or missing
                meta = TABLE_META.get(skey, {})
                rc = add_word_table(doc, skey, None, None)
                table_stats[skey] = (0, 0)

    return table_stats, figures_found


def build_si_only(doc, data):
    """Build a standalone SI document with S1-S8."""
    setup_styles(doc)
    for section in doc.sections:
        section.top_margin    = Inches(0.9)
        section.bottom_margin = Inches(0.9)
        section.left_margin   = Inches(0.9)
        section.right_margin  = Inches(0.9)

    # Title block
    p = doc.add_paragraph(style="Title")
    p.add_run("Supplementary Information")
    p2 = doc.add_paragraph()
    r = p2.add_run(
        "CoupledMD: a uniform-protocol molecular dynamics web resource for comparative "
        "analysis of 222 GPCR–G-protein ternary complexes."
    )
    r.bold = True; r.font.size = Pt(11)

    doc.add_paragraph(
        "All tables are computed from the CoupledMD pipeline outputs with no manual "
        "editing. Source CSV files are listed in each table caption. Values marked 'n/a' "
        "indicate data not available for that system; the Gi_8HK2 system reports "
        "length_per_replica_ns = 2 (possible data-entry anomaly — flagged in notes)."
    ).paragraph_format.space_after = Pt(12)

    table_stats = {}
    for skey in ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"]:
        h, r, status = data.get(skey, (None, None, "missing"))
        rc = add_word_table(doc, skey, h if status == "ok" else None,
                                       r if status == "ok" else None)
        table_stats[skey] = rc

    return table_stats


# ── compile check ─────────────────────────────────────────────────────────────

def write_compile_check(main_stats, si_stats, combined_stats, figures_found,
                        data, path):
    lines = [
        "# COMPILE_CHECK.md — Assembly validation report",
        f"Generated by: assemble_tables.py",
        "",
        "## Assertion 1: T1-T3 as native table objects in main docx",
        "",
    ]

    all_pass = True
    for key in ["T1", "T2", "T3"]:
        rc = main_stats.get(key)
        h, r, status = data.get(key, (None, None, "missing"))
        if rc and rc[0] > 0:
            lines.append(f"- **{key}**: PASS — {rc[0]} data rows × {rc[1]} columns  "
                         f"(source: {TABLE_META[key]['file'].name if TABLE_META[key]['file'] else 'n/a'})")
        else:
            lines.append(f"- **{key}**: FAIL — table absent or empty (status: {status})")
            all_pass = False

    lines += [
        "",
        "## Assertion 2: S1-S8 in SI docx (or explicitly marked deferred)",
        "",
    ]
    for key in ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"]:
        rc = si_stats.get(key)
        h, r, status = data.get(key, (None, None, "missing"))
        meta = TABLE_META.get(key, {})
        fpath = meta.get("file")
        if status == "deferred":
            lines.append(f"- **{key}**: PASS (deferred) — placeholder and caption present")
        elif rc and rc[0] > 0:
            fname = Path(fpath).name if fpath else "n/a"
            lines.append(f"- **{key}**: PASS — {rc[0]} data rows × {rc[1]} columns  "
                         f"(source: {fname})")
        else:
            lines.append(f"- **{key}**: FAIL — table absent or empty (status: {status})")
            all_pass = False

    lines += [
        "",
        "## Assertion 3: Figures in combined docx",
        "",
    ]
    for fn in [1, 2, 3, 4, 5]:
        if fn in figures_found:
            lines.append(f"- Figure {fn}: PASS")
        else:
            lines.append(f"- Figure {fn}: FAIL — not found in document")
            all_pass = False

    lines += [
        "",
        "## Table row/column inventory",
        "",
        "| Table | Source file | Data rows | Columns | Status |",
        "|-------|-------------|-----------|---------|--------|",
    ]
    for key in ["T1", "T2", "T3", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"]:
        meta = TABLE_META.get(key, {})
        fpath = meta.get("file")
        fname = Path(fpath).name if fpath else "n/a"
        h, r, status = data.get(key, (None, None, "missing"))
        src_rows = len(r) if r else 0
        src_cols = len(h) if h else 0
        rc = combined_stats.get(key, (0, 0))
        disp_rows, disp_cols = rc
        if status == "deferred":
            lines.append(f"| {key} | n/a | n/a | n/a | deferred |")
        elif status == "ok":
            lines.append(f"| {key} | {fname} | {src_rows} ({disp_rows} displayed) "
                         f"| {src_cols} ({disp_cols} displayed) | ok |")
        else:
            lines.append(f"| {key} | {fname} | n/a | n/a | {status} |")

    lines += [
        "",
        "## Output files",
        "",
    ]
    for fname, desc in [
        ("versions/manuscript_v1.4.1.docx",          "Main text + T1-T3 embedded"),
        ("versions/SI_v1.0.0.docx",                  "Standalone SI with S1-S8"),
        ("versions/manuscript_v1.4.1_combined.docx",  "Combined: main + SI appended"),
    ]:
        fpath = HERE / fname
        if fpath.exists():
            lines.append(f"- **{fname}**: {fpath.stat().st_size:,} bytes — {desc}")
        else:
            lines.append(f"- **{fname}**: MISSING — {desc}")
            all_pass = False

    lines += [
        "",
        f"## Overall: {'✓ ALL ASSERTIONS PASS' if all_pass else '✗ ONE OR MORE ASSERTIONS FAILED'}",
    ]

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return all_pass


# ── entry point ───────────────────────────────────────────────────────────────

def main():
    print("Loading table data...")
    data = load_all()
    for key, (h, r, status) in data.items():
        n = len(r) if r else 0
        print(f"  {key}: {status}  ({n} rows)")

    lines = MD_SRC.read_text(encoding="utf-8").splitlines()
    print(f"\nMarkdown source: {len(lines)} lines")

    # ── 1: main text + T-tables only ─────────────────────────────────────
    print("\nBuilding manuscript_v1.4.1.docx (main + T1-T3)...")
    doc_main = Document()
    main_stats, figures_main = build_main(doc_main, lines, data, include_si=False)
    out_main = VERSIONS / "manuscript_v1.4.1.docx"
    doc_main.save(str(out_main))
    print(f"  wrote {out_main}  ({out_main.stat().st_size:,} bytes)")

    # ── 2: SI only ────────────────────────────────────────────────────────
    print("\nBuilding SI_v1.0.0.docx (S1-S8)...")
    doc_si = Document()
    si_stats = build_si_only(doc_si, data)
    out_si = VERSIONS / "SI_v1.0.0.docx"
    doc_si.save(str(out_si))
    print(f"  wrote {out_si}  ({out_si.stat().st_size:,} bytes)")

    # ── 3: combined ────────────────────────────────────────────────────────
    print("\nBuilding manuscript_v1.4.1_combined.docx (main + SI)...")
    doc_comb = Document()
    comb_stats, figures_comb = build_main(doc_comb, lines, data, include_si=True)
    out_comb = VERSIONS / "manuscript_v1.4.1_combined.docx"
    doc_comb.save(str(out_comb))
    print(f"  wrote {out_comb}  ({out_comb.stat().st_size:,} bytes)")

    # ── 4: COMPILE_CHECK.md ────────────────────────────────────────────────
    print("\nWriting COMPILE_CHECK.md...")
    check_path = HERE / "COMPILE_CHECK.md"
    # merged SI stats from combined for combined-doc assertions
    merged_si = {**comb_stats}
    ok = write_compile_check(
        main_stats=main_stats,
        si_stats=si_stats,
        combined_stats={**main_stats, **si_stats},
        figures_found=figures_comb,
        data=data,
        path=check_path
    )
    print(f"  wrote {check_path}")
    print(f"\n{'✓ ALL ASSERTIONS PASS' if ok else '✗ ONE OR MORE FAILED'}")

    # snapshot md source
    shutil.copy(MD_SRC, VERSIONS / "manuscript_v1.4.1.md")
    print(f"  md snapshot → versions/manuscript_v1.4.1.md")


if __name__ == "__main__":
    main()
