#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from docx import Document


HERE = Path(__file__).resolve().parent


def norm(text: str) -> str:
    return " ".join(text.split())


MANUSCRIPT_REPLACEMENTS = {
    norm("Figure 1 is intended to be read as the scope statement for the resource. Panel A shows that the release is broad across Class A and Class B receptors while remaining concentrated in the G-protein families currently represented by available active-state complex structures. Panel B identifies receptors represented with more than one G-protein family, indicating where the dataset supports receptor-level comparison without implying a coupling mechanism. Panel C separates ligand-bearing and apo systems so that users can select systems appropriate for ligand-aware or ligand-independent workflows. Panel D lists receptors with the largest representation in clean-v1, and Panel E documents the release boundary by showing the 208 included systems and 14 held-back systems from the 222-system designed inventory."):
        "Figure 1 is intended to be read as the scope statement for the resource. Panel A quantifies the class-by-family coverage of the 208-system clean-v1 cohort. Panel B highlights the receptors represented across the largest number of systems and marks those sampled with more than one G-protein family, indicating where within-receptor comparative reuse is immediately possible without implying a coupling mechanism. Panel C separates ligand-present and apo or no-ligand systems by family so that users can identify ligand-aware and ligand-independent subsets. Panel D expands this reuse view to the 42 most represented receptors, where larger and accent-colored markers identify receptors sampled across multiple G-protein-family contexts. Panel E keeps the release boundary explicit by contrasting the 208 included systems with the 14 held-back systems and by grouping the held-back records into nonstandard-length or missing/incomplete-output categories.",
    norm("Figure 2 describes how a user should navigate the data product. Panel A organizes the archive into manifest, metadata, per-system topology, trajectory, reduced-trajectory, feature, pocket, QC, code and web/API snapshot components. Panel B maps the same organization onto the per-system metadata fields, linking receptor, G-protein, ligand/state, replica and file/QC information. Panel C makes the access hierarchy explicit: the archive is the stable record for citation and reproducibility, whereas the portal and API are access layers. Panel D documents the intended portal-facing route for browsing, visualization, download and API discovery; this panel is replaced with a final screenshot before submission."):
        "Figure 2 describes how a user should navigate the data product. Panel A organizes the archive into manifest, metadata, per-system topology, trajectory, reduced-trajectory, feature, pocket, QC, code and web/API snapshot components. Panel B maps the same organization onto the per-system metadata fields, linking receptor, G-protein, ligand/state, replica and file/QC information. Panel C makes the access hierarchy explicit: the archive is the stable record for citation and reproducibility, whereas the portal and API are access layers. Panel D translates that hierarchy into a publication-ready portal-access schematic showing search, filtering, structure viewing, download actions and API entry points, so the figure remains interpretable even before a final live screenshot is inserted.",
    norm("Together, Figure 3A and 3B provide the main technical-validation view for pocket-derived records. The recovery panel asks whether known ligand-accessible receptor pockets are recovered at the expected location often enough to support reuse of the pocket annotations. The pocket-count panel asks whether the pocket-detection layer produces a plausible and trackable number of records per system rather than sparse or unstable outputs. Figure 3C places CoupledMD beside related GPCR and general-protein MD resources to contextualize scale, but the comparison is descriptive and remains conditional on final benchmark verification."):
        "Together, Figure 3A and 3B provide the main technical-validation view for pocket-derived records. The recovery panel asks whether known ligand-accessible receptor pockets are recovered at the expected location often enough to support reuse of the pocket annotations. The pocket-count panel asks whether the pocket-detection layer produces a plausible and trackable number of records per system rather than sparse or unstable outputs. Figure 3C then places CoupledMD beside a single-receptor GPCR trajectory resource and a large general-protein MD resource to contextualize the niche that this release occupies: fewer systems than domain-scale repositories, but unusually broad sampling for membrane-embedded GPCR/G-protein complexes. This comparison is descriptive and is not used as a quality benchmark.",
    norm("Reduced-trajectory frame counts were 2,500 frames for 205 systems, 2,501 frames for two systems and 200 frames for one system. The short reduced visualization record corresponds to Gs_3SN6; the production metadata for that system remain in the clean-v1 cohort and the reduced-record difference is flagged. Systems with WARN status (Gi_8J22, Gq_7XJL and Gs_7F4H) carry only minor scatter warnings and no hard audit failure. Figure 4 summarizes gateway annotation coverage, reduced-trajectory audit outcomes, frame-count completeness and held-back categories as the QC and completeness view of the release."):
        "Reduced-trajectory frame counts were 2,500 frames for 205 systems, 2,501 frames for two systems and 200 frames for one system. The short reduced visualization record corresponds to Gs_3SN6; the production metadata for that system remain in the clean-v1 cohort and the reduced-record difference is flagged. Systems with WARN status (Gi_8J22, Gq_7XJL and Gs_7F4H) carry only minor scatter warnings and no hard audit failure. Figure 4 summarizes gateway annotation coverage, family-level orthosteric-recovery rates, gateway open-fraction distributions and dataset completeness as the QC and integrity view of the release, while the reduced-trajectory audit details remain documented in Supplementary Tables S15-S17 and the figure callout.",
    norm("Figure 4 is the release-integrity figure. Panel A catalogs derived TM-gateway annotation values across the 208 systems as machine-readable records, with family grouping used only to organize the display. Panels B and C report reduced-trajectory usability checks: the PBC audit found 205 OK systems, 3 WARN systems and no hard failures, while the frame-count panel identifies the expected 2,500-frame reduced records and the few nonstandard counts. Panel D connects these QC results to the transparent release boundary by summarizing the 14 held-back systems and visualization flags. These panels document completeness and known caveats; they are not used to infer biological differences among G-protein families."):
        "Figure 4 is the release-integrity figure. Panel A catalogs derived TM-gateway open-fraction annotations across the 208 systems as machine-readable records, with family grouping used only to organize the display. Panel B restates family-level orthosteric-pocket recovery rates as a compact structural-fidelity benchmark for the derived pocket layer. Panel C summarizes the open-fraction distributions for the seven transmembrane gateway interfaces across the full cohort, showing that the gateway layer spans a broad dynamic range rather than collapsing to a single trivial state. Panel D connects these annotation summaries to the transparent release boundary by contrasting the 208 included systems with the 14 held-back systems and by reporting the reduced-trajectory integrity outcome as a compact callout. These panels document completeness and annotation behavior; they are not used to infer biological differences among G-protein families.",
    norm("Example reuse workflows include filtering systems by GPCR class, G-protein family, receptor name, UniProt accession, PDB identifier or ligand annotation; retrieving reduced structures and trajectories for visualization; joining GPCRdb-mapped pocket residues to external receptor annotations; and using API endpoints to build reproducible system lists before downloading full trajectories from the archive. Figure 5 summarizes the consensus pocket annotations, GPCRdb-position anchors and proxy-validation views distributed with the resource as reusable annotation records. Supplementary Figure S3 provides the portal/API access workflow. These workflows support rather than substitute for downstream analyses, including those that may interpret family-resolved or ligand-specific signatures."):
        "Example reuse workflows include filtering systems by GPCR class, G-protein family, receptor name, UniProt accession, PDB identifier or ligand annotation; retrieving reduced structures and trajectories for visualization; joining GPCRdb-mapped pocket residues to external receptor annotations; and using API endpoints to build reproducible system lists before downloading full trajectories from the archive. Figure 5 summarizes the consensus pocket atlas distributed with the resource, including cluster-level occupancy, anatomical zoning, reusable GPCRdb anchors, validation context and high-scoring nomination examples. Supplementary Figure S3 provides the portal/API access workflow. These workflows support rather than substitute for downstream analyses, including those that may interpret family-resolved or ligand-specific signatures.",
    norm("Figure 5 describes the pocket-annotation layer as a reusable data product. Panels A and B summarize consensus pocket clusters by anatomical zone and record how many cluster members contribute to each zone. Panel C lists reusable GPCRdb-position anchors that appear in pocket-cluster cores, allowing residue-level joins across receptors without relying only on receptor-specific numbering. Panel D restates orthosteric recovery as a proxy-validation view for pocket records, and Panel E provides example receptors with broad pocket-cluster coverage as workflow illustrations. These outputs can support prioritization or benchmarking workflows, but the manuscript does not treat them as experimental druggability validation or as mechanistic discoveries."):
        "Figure 5 describes the pocket-annotation layer as a reusable data product. Panel A is reserved for a representative structural or portal-facing snapshot during final layout. Panel B maps consensus druggable pocket clusters by receptor coverage and mean occupancy, with marker size reflecting cluster volume and color indicating anatomical zone. Panel C counts cluster members across orthosteric, transmembrane-core allosteric, intracellular-allosteric and related zones. Panel D lists the GPCRdb generic positions that recur most often in the orthosteric and druggable cluster cores, allowing residue-level joins across receptors without relying only on receptor-specific numbering. Panel E restates family-level orthosteric recovery as a validation view for the distributed pocket records, and Panel F highlights nomination examples with the highest proxy scores together with example receptors. These outputs can support prioritization or benchmarking workflows, but the manuscript does not treat them as experimental druggability validation or as mechanistic discoveries.",
    norm("Figure 1. Coverage and reuse landscape of the CoupledMD clean-v1 release. (A) Class × G-protein family coverage across 208 systems. (B) Receptors represented with more than one G-protein family in clean-v1. (C) Ligand-bearing versus apo systems by family. (D) Top receptors by system count, with bubble size encoding G-protein-family breadth. (E) Release boundary: 208 included and 14 held back from 222 designed systems; held-back categories are detailed in Supplementary Table S2. Composition is shown for resource description; biological interpretation of family or ligand patterns is outside the scope of this Data Descriptor."):
        "Figure 1. Coverage and reuse landscape of the CoupledMD clean-v1 release. (A) Class × G-protein-family coverage across 208 systems. (B) Receptors represented across the largest number of systems, with multi-family receptors highlighted as direct within-receptor reuse opportunities. (C) Ligand-present versus apo or no-ligand systems by family. (D) Receptor reuse landscape for the most represented receptors, with accent-colored larger markers denoting receptors sampled across more than one G-protein family. (E) Release boundary: 208 included and 14 held back from 222 designed systems, with held-back records grouped into major exclusion categories. Composition is shown for resource description; biological interpretation of family or ligand patterns is outside the scope of this Data Descriptor.",
    norm("Source asset: scidata_figures/scidata_figure5_community_landscape.pdf"):
        "Source asset: scidata_figures/new_figure1_community_landscape.pdf",
    norm("Figure 2. Repository organization, metadata schema and three-tier access model of CoupledMD. (A) Archive hierarchy, including manifest, metadata, systems, topology, trajectories, reduced files, features, pocket records, QC records, code and web/API snapshots. (B) Per-system metadata schema for system, receptor, G protein, ligand/state, replicas, files and QC status. (C) Archive-first access model: the stable archive is the citable record, while the web portal and REST API provide browse, visualization and programmatic access. (D) Portal access layer showing system browse, viewer, download and API endpoints. File formats and field definitions are detailed in Main Tables 2 and 3; the placeholder in panel D is replaced with a real portal screenshot at submission."):
        "Figure 2. Repository organization, metadata schema and three-tier access model of CoupledMD. (A) Archive hierarchy, including manifest, metadata, systems, topology, trajectories, reduced files, features, pocket records, QC records, code and web/API snapshots. (B) Per-system metadata schema for system, receptor, G protein, ligand/state, replicas, files and QC status. (C) Archive-first access model: the stable archive is the citable record, while the web portal and REST API provide browse, visualization and programmatic access. (D) Portal-access schematic showing search, filters, structure viewing, download actions and API entry points. File formats and field definitions are detailed in Main Tables 2 and 3.",
    norm("Source asset: scidata_figures/scidata_figure2_data_records.pdf"):
        "Source asset: scidata_figures/new_figure2_data_records.pdf",
    norm("Figure 3. Technical validation of the CoupledMD clean-v1 release. (A) Best per-system orthosteric-pocket frequency by G-protein family; the dashed line marks the 0.85 recovery threshold. (B) Per-system pocket-count distribution by family. (C) Dataset-scale comparison of systems and aggregate sampling against related GPCR and general-protein MD resources; benchmark values are verified with citations before submission or demoted to a supplementary figure. Validation is technical and does not interpret biological mechanism."):
        "Figure 3. Technical validation and dataset-scope context for the CoupledMD clean-v1 release. (A) Best per-system orthosteric-pocket frequency by G-protein family; the dashed line marks the 0.85 recovery threshold and recovery percentages are annotated by family. (B) Per-system pocket-count distribution by family, summarized as median and interquartile range with individual-system points overlaid. (C) Descriptive comparison of system count and aggregate sampling against representative single-receptor GPCR and general-protein MD resources to contextualize the scope of CoupledMD. Validation is technical and does not interpret biological mechanism.",
    norm("Source asset: scidata_figures/scidata_figure3_validation_ridgeline.pdf"):
        "Source asset: scidata_figures/new_figure3_validation_ridgeline.pdf",
    norm("Figure 4. QC and completeness summary of the CoupledMD clean-v1 release. (A) Derived TM-gateway open-fraction annotations across 208 systems, grouped by G-protein family for organizational convenience; family-resolved differences in panel A are not interpreted here. (B) Reduced-trajectory PBC audit outcomes (205 OK, 3 WARN, 0 hard failures). (C) Reduced-trajectory frame counts (205 systems at 2,500 frames, 2 at 2,501 frames, 1 at 200 frames). (D) Held-back cohort from the 222 designed systems and visualization-flag table; full reasons are listed in Supplementary Table S2. Biological interpretation of the gateway annotations is outside the scope of this Data Descriptor."):
        "Figure 4. QC and completeness summary of the CoupledMD clean-v1 release. (A) Derived TM-gateway open-fraction annotations across 208 systems, grouped by G-protein family for organizational convenience; family-resolved differences in panel A are not interpreted here. (B) Orthosteric-pocket recovery rate by G-protein family, shown as a compact structural-fidelity benchmark for the derived pocket layer. (C) Open-fraction distributions for the seven transmembrane gateway interfaces across the clean-v1 cohort. (D) Included versus held-back systems with major exclusion categories, accompanied by a reduced-trajectory integrity callout summarizing the PBC audit outcome. Biological interpretation of the gateway annotations is outside the scope of this Data Descriptor.",
    norm("Source asset: scidata_figures/scidata_figure4_qc.pdf"):
        "Source asset: scidata_figures/new_figure4_qc.pdf",
    norm("Figure 5. Consensus pocket annotations distributed with CoupledMD. (A) Consensus pocket clusters summarized by zone (TM-core allosteric, intracellular allosteric, extracellular vestibule). (B) Cluster-member counts by zone. (C) Reusable GPCRdb-position anchors appearing in pocket cluster cores. (D) Orthosteric recovery as a proxy-validation view. (E) Example receptors with broad pocket-cluster coverage, shown as workflow illustrations. Pocket clusters and proxy scores are derived annotations and are not experimental druggability validation; biological or pharmacological interpretation is outside the scope of this Data Descriptor."):
        "Figure 5. Pocket-atlas annotations distributed with CoupledMD. (A) Reserved slot for a representative structural or portal-facing snapshot in the final composed figure. (B) Consensus druggable pocket clusters mapped by receptor coverage and mean occupancy, with point size reflecting cluster volume and color indicating anatomical zone. (C) Cluster-member counts by anatomical zone. (D) Reusable GPCRdb-position anchors appearing most frequently in orthosteric and druggable cluster cores. (E) Orthosteric recovery by family as a validation view for the pocket layer. (F) High-scoring drug-design nomination examples with representative receptors. Pocket clusters and proxy scores are derived annotations and are not experimental druggability validation; biological or pharmacological interpretation is outside the scope of this Data Descriptor.",
    norm("Source asset: scidata_figures/scidata_figure6_drug_design_pocket_atlas.pdf"):
        "Source asset: scidata_figures/new_figure5_drug_design_pocket_atlas.pdf",
    norm("Supplementary Figure S1. Extended GPCR/G-protein coverage overview. Extended overview of clean-v1 receptor and G-protein-family coverage. The figure summarizes class-to-family coupling coverage, receptor-level multi-family representation, receptor counts and release-boundary information as supporting context for Figure 1. The figure is provided as a coverage summary only; biological interpretation of family or receptor patterns is outside the scope of this Data Descriptor."):
        "Supplementary Figure S1. Receptor-level coupling-topology dendrogram. Circular dendrogram of the 174 clean-v1 receptors clustered by presence or absence across the four major G-protein families. Leaf ticks are colored by single-family assignment or by multi-family representation, and each leaf is labeled by a representative four-letter PDB identifier. The figure provides receptor-level coupling-topology context for Figure 1 without implying mechanistic similarity among clustered receptors.",
    norm("Supplementary Figure S1 provides the broader coverage context behind the compact main Figure 1 view. It is useful for readers who want to inspect how the 208 clean-v1 systems are distributed across receptor classes, G-protein families and receptor-level representation before using the per-system tables. The figure also reinforces the release-boundary logic by keeping the clean-v1 cohort separate from held-back systems, so readers can distinguish dataset composition from unresolved or excluded records."):
        "Supplementary Figure S1 provides the receptor-level context behind the compact counts in Figure 1. By clustering receptors according to whether they appear with Gi/o, Gs, Gq/11 or G12/13 partners, the figure separates single-family receptors from the smaller set of multi-family receptors that are especially suitable for within-receptor comparative reuse. The circular layout also allows readers to scan representative PDB coverage around the rim without consulting the full per-system tables.",
    norm("Source asset: scidata_figures/scidata_figure1_overview_circos.pdf"):
        "Source asset: scidata_figures/new_figureS1_dendrogram.pdf",
    norm("Supplementary Figure S2. Portal, archive and API coverage. Summary of archive, portal and API coverage for the clean-v1 release. Panels summarize the two-tier data product, current portal/API record availability, OpenAPI endpoint groups and archive/portal completeness information. Final file counts, sizes and checksum status are updated against the frozen archive before submission."):
        "Supplementary Figure S2. Portal, archive and API coverage. (A) Portal-file availability by record type, separating present and missing system-level records. (B) Two-tier data-product size comparison between the production archive and the portal/API layer. (C) Documented REST surface grouped by manuscript-relevant use categories. Final file counts, sizes and checksum status are updated against the frozen archive before submission.",
    norm("Supplementary Figure S2 expands the access and completeness information that is compressed in Figure 2. It separates stable archive contents from portal/API-facing records, reports which record classes are currently available through the access layer, and documents endpoint-group coverage from the OpenAPI snapshot. This figure is intended as an operational completeness view; final file counts, sizes and checksum status are updated against the frozen archive before submission."):
        "Supplementary Figure S2 expands the access and completeness information that is compressed in Figure 2. It reports which portal-facing record classes are currently available, contrasts the scale of the archival and web-facing layers, and summarizes how the documented REST endpoints are distributed across user-facing use categories. This figure is intended as an operational completeness view; final file counts, sizes and checksum status are updated against the frozen archive before submission.",
    norm("Source asset: scidata_figures/scidata_figure10_portal_archive_coverage.pdf"):
        "Source asset: scidata_figures/new_figure_s2_portal_archive_coverage.pdf",
    norm("Supplementary Figure S3. Portal/API access workflow. Workflow for interactive and programmatic access to CoupledMD. The figure shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization, downloads and API retrieval. The workflow illustrates access routes and does not substitute for the stable archive record."):
        "Supplementary Figure S3. Portal/API access workflow. Workflow for interactive and programmatic access to CoupledMD. Panel A shows the user-facing browsing route from search and filtering to per-system pages, reduced-trajectory visualization and downloads. Panel B groups the programmatic API layers into status/citation, system, derived-record, visualization and consensus endpoints. Panel C restates the archive-first access model in which the stable repository remains the citable record. The workflow illustrates access routes and does not substitute for the stable archive record.",
    norm("Supplementary Figure S3 shows the practical reuse path for a user who starts from the web portal or API rather than from the full archive. The workflow connects system browsing, filtering, per-system metadata, reduced-trajectory visualization, download actions and API retrieval into a single access route. It is included to document usability and reproducibility of access, while the stable archive remains the authoritative source for citation and long-term reuse."):
        "Supplementary Figure S3 shows the practical reuse path for a user who starts from the web portal or API rather than from the full archive. The workflow connects system browsing, filtering, per-system metadata, reduced-trajectory visualization, download actions and API retrieval into a single access route, while also making clear that the portal and API sit downstream of the authoritative archive. It is included to document usability and reproducibility of access, while the stable archive remains the source for citation and long-term reuse.",
    norm("Source asset: scidata_figures/scidata_suppfigS3_portal_access_workflow_draft.svg"):
        "Source asset: scidata_figures/new_figureS3_portal_access.svg",
}


SI_REPLACEMENTS = {
    norm("Supplementary Figure S1. Extended GPCR/G-protein coverage overview. Extended overview of clean-v1 receptor and G-protein-family coverage. The figure summarizes class-to-family coupling coverage, receptor-level multi-family representation, recovery/sampling tracks and receptors represented across more than one G-protein family. The panel is provided as a resource-composition summary; family patterns are not interpreted as biological mechanisms in this Data Descriptor."):
        "Supplementary Figure S1. Receptor-level coupling-topology dendrogram. Circular dendrogram of the 174 clean-v1 receptors clustered by presence or absence across the four major G-protein families. Leaf ticks are colored by single-family assignment or by multi-family representation, and each leaf is labeled by a representative four-letter PDB identifier. The figure provides receptor-level coupling-topology context for Figure 1 without implying mechanistic similarity among clustered receptors.",
    norm("Source asset: scidata_figures/scidata_figure1_overview_circos.pdf"):
        "Source asset: scidata_figures/new_figureS1_dendrogram.pdf",
    norm("Supplementary Figure S2. Portal, archive and API coverage. Summary of archive, portal and API coverage for the clean-v1 release. Panels summarize the two-tier data product, current portal/API record availability, OpenAPI endpoint groups and the archive-first access model. The figure supports the Data Records and Usage Notes sections of the main manuscript by documenting how users can move from system search to metadata, derived records, reduced visualization files and archived full trajectories."):
        "Supplementary Figure S2. Portal, archive and API coverage. Summary of archive, portal and API coverage for the clean-v1 release. Panel A reports portal-file availability by record type, Panel B compares the size of the production archive with the portal/API layer, and Panel C groups the documented REST endpoints by manuscript-relevant use category. The figure supports the Data Records and Usage Notes sections by documenting how operational coverage is distributed across the archive and access layers.",
    norm("Source asset: scidata_figures/scidata_figure10_portal_archive_coverage.pdf"):
        "Source asset: scidata_figures/new_figure_s2_portal_archive_coverage.pdf",
    norm("Supplementary Figure S3. Portal/API access workflow. Workflow for interactive and programmatic access to CoupledMD. The figure shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization and selected downloads, together with REST API layers for status/citation records, system metadata, derived records, visualization files and consensus summaries. The stable archive remains the citable data record."):
        "Supplementary Figure S3. Portal/API access workflow. Workflow for interactive and programmatic access to CoupledMD. Panel A shows the user-facing route from system search and filtering to per-system metadata, reduced-trajectory visualization and selected downloads, Panel B groups the REST API layers for status/citation records, system metadata, derived records, visualization files and consensus summaries, and Panel C restates the archive-first access model. The stable archive remains the citable data record.",
    norm("Source asset: scidata_figures/scidata_suppfigS3_portal_access_workflow_draft.svg"):
        "Source asset: scidata_figures/new_figureS3_portal_access.svg",
}


def patch_docx(path: Path, replacements: dict[str, str]) -> int:
    doc = Document(path)
    count = 0
    for paragraph in doc.paragraphs:
        key = norm(paragraph.text)
        if key in replacements:
            paragraph.text = replacements[key]
            count += 1
    doc.save(path)
    return count


def main() -> None:
    targets = [
        (HERE / "manuscript_v3.docx", MANUSCRIPT_REPLACEMENTS),
        (HERE / "scidata_figures" / "manuscript_v3.docx", MANUSCRIPT_REPLACEMENTS),
        (HERE / "si_v3.docx", SI_REPLACEMENTS),
        (HERE / "scidata_figures" / "si_v3.docx", SI_REPLACEMENTS),
    ]
    for path, replacements in targets:
        updated = patch_docx(path, replacements)
        print(f"{path}: updated {updated} paragraphs")


if __name__ == "__main__":
    main()
